const Kosakata = {
	bab1: [
		["私", "わたし", "saya"],
		["", "あなた", "Anda"],
		["あの人", "あのひと", "orang itu, beliau"],
		["あの方", "あのかた", "bentuk sopan orang itu / beliau"],
		["", "〜さん", "Sdr.~, Bapak~, Ibu~"],
		["", "〜ちゃん", "akhiran yang dipakai untuk anak-anak pengganti ~さん"],
		["〜人", "〜じん", "orang ~"],
		[
			"先生",
			"せんせい",
			"guru, dosen (tidak dipakai jika\nmenyebutkan pekerjaan sendiri)",
		],
		["教師", "きょうし", "guru, dosen"],
		["学生", "がくせい", "mahasiswa"],
		["会社員", "かいしゃいん", "karyawan perusahaan"],
		[
			"社員",
			"しゃいん",
			"karyawan perusahaan\n(dipakai bersama dengan nama perusahaan.)",
		],
		["銀行員", "ぎんこういん", "pegawai bank"],
		["医者", "いしゃ", "dokter"],
		["研究者", "けんきゅうしゃ", "peneliti"],
		["大学", "だいがく", "universitas"],
		["病院", "びょういん", "rumah sakit"],
		["誰", "だれ", "siapa"],
		["", "どなた", "bentuk sopan dari siapa"],
		["歳", "さい", "~ tahun"],
		["何歳", "なんさい", "umur berapa"],
		["", "おいくつ", "bentuk sopan menanyakan umur"],
		["", "はい", "ya"],
		["", "いいえ", "tidak, bukan"],
		["", "アメリカ", "Amerika Serikat"],
		["", "イギリス", "Inggris"],
		["", "インド", "India"],
		["", "インドネシア", "Idonesia"],
		["韓国", "かんこく", "Korea Selatan"],
		["", "タイ", "Thailan"],
		["中国", "ちゅうごく", "Cina"],
		["", "ドイツ", "Jerman"],
		["日本", "にほん", "Jepang"],
		["", "ブラジル", "Brasil"],
	],
	bab2: [
		["", "これ", "ini (benda)"],
		["", "それ", "itu (benda)"],
		["", "あれ", "itu (benda)"],
		["", "この〜", "~ ini (menerangkan benda)"],
		["", "その〜", "~ itu (menerangkan benda)"],
		["", "あの〜", "~ itu (menerangkan benda)"],
		["本", "ほん", "buku"],
		["辞書", "じしょ", "kamus"],
		["雑誌", "ざっし", "majalah"],
		["新聞", "しんぶん", "koran, surat kabar"],
		["", "ノート", "buku tulis, buku catatan"],
		["手帳", "てちょう", "buku agenda"],
		["名刺", "めいし", "katu nama"],
		["", "カード", "katu"],
		["鉛筆", "えんぴつ", "pensil"],
		["", "ボールペン", "bolpoin"],
		["", "シャープペンシル", "pencil mekanik, pensil isi ulang"],
		["鍵", "かぎ", "kunci"],
		["時計", "とけい", "jam, arloji"],
		["傘", "かさ", "payung"],
		["", "かばん", "tas"],
		["", "テレビ", "televisi"],
		["", "ラジオ", "radio"],
		["", "カメラ", "kamera"],
		["", "コンピューター", "komputer, PC"],
		["車", "くるま", "mobil"],
		["机", "つくえ", "meja, ,eja tulis"],
		["椅子", "いす", "kursi"],
		["", "チョコレート", "coklat"],
		["", "コーヒー", "kopi"],
		["お土産", "おみやげ", "oleh-oleh"],
		["英語", "えいご", "bahasa Inggris"],
		["日本語", "にほんご", "bahasa Jepang"],
		["語", "〜ご", "bahasa ~"],
		["何", "なに/なん", "apa"],
		["", "そう", "begitu"],
	],
	bab3: [
		["", "ここ", "di sini"],
		["", "そこ", "di situ"],
		["", "あそこ", "di sana"],
		["", "どこ", "(di) mana"],
		["", "こちら", "bentuk sopan di sini"],
		["", "そちら", "bentuk sopan di situ"],
		["", "あちら", "bentuk sopan di sana"],
		["", "どちら", "bentuk sopan di mana"],
		["教室", "きょうしつ", "ruang kelas"],
		["食堂", "しょくどう", "ruang makan, rumah makan, kantin"],
		["事務所", "じむしょ", "kantor"],
		["会議室", "かいぎしつ", "ruang rapat"],
		["受付", "うけつけ", "meja informasi"],
		["", "ロビー", "ruang tunggu, lobi"],
		["部屋", "へや", "kamar"],
		["お手洗い", "トイレ,おてあらい", "kamar kecil, toilet, W.C."],
		["階段", "かいだん", "tangga"],
		["", "エレベーター", "lift"],
		["", "エスカレーター", "tangga berjalan, eskalator"],
		["自動販売機", "じどうはんばいき", "mesin jual otomatis"],
		["電話", "でんわ", "telepon"],
		["お国", "おくに", "negara, negeri"],
		["会社", "かいしゃ", "perusahaan"],
		["", "うち", "rumah"],
		["靴", "くつ", "sepatu"],
		["", "ネクタイ", "dasi"],
		["", "ワイン", "anggur"],
		["売り場", "うりば", "tempat penjualan"],
		["地下", "ちか", "bewah tanah, basement"],
		["階", "〜かい", "lantai-, tingkat-"],
		["何階", "なんがい", "lantai berapa, tingkat berapa"],
		["円", "〜えん", "-yen"],
		["", "いくら", "berapa"],
		["百", "ひゃく", "ratus"],
		["千", "せん", "ribu"],
		["万", "まん", "puluh ribu"],
		["", "イタリア", "Italia"],
		["", "スイス", "Swiss"],
		["", "フランス", "Perancis"],
		["", "ジャカルタ", "Jakarta"],
		["", "バンコク", "Bangkok"],
		["", "ベルリン", "Berlin"],
	],
	bab4: [
		["起きます", "おきます", "bangun"],
		["寝ます", "ねます", "tidur"],
		["働きます", "はたらきます", "bekerja"],
		["休みます", "やすみます", "beristirahat, libur"],
		["勉強します", "べんきょうします", "belajar"],
		["終わります", "おわります", "selesai"],
		["", "デパート", "toserba"],
		["銀行", "ぎんこう", "bank"],
		["郵便局", "ゆうびんきょく", "kantor pos"],
		["図書館", "としょかん", "perpustakaan"],
		["美術館", "びじゅつかん", "gedung kesenian"],
		["今", "いま", "sekarang"],
		["時", "〜じ", "jam-, pukul-"],
		["分", "〜ふん / ぷん", "-menit"],
		["半", "はん", "setengah"],
		["何時", "なんじ", "jam berapa, pukul berapa"],
		["何分", "なんふん / なんぷん", "berapa menit"],
		["午前", "ごぜん", "a.m. (waktu sebelum jam 12 siang)"],
		["午後", "ごご", "p.m. (waktu setelah jam 12 siang)"],
		["朝", "あさ", "pagi"],
		["昼", "ひる", "siang"],
		["晩 / 夜", "ばん / よる", "malam"],
		["一昨日", "おととい", "dura hari yang lalu, kemarin lusa"],
		["昨日", "きのう", "kemarin"],
		["今日", "きょう", "hari ini"],
		["明日", "あした", "besok"],
		["明後日", "あさって", "lusa"],
		["今朝", "けさ", "pagi ini, tadi pagi"],
		["今晩", "こんばん", "malam ini, nanti malam"],
		["休み", "やすみ", "istrahat, cuti, libur"],
		["昼休み", "ひるやすみ", "istrahat siang"],
		["試験", "しけん", "ujian"],
		["会議", "かいぎ", "rapat"],
		["映画", "えいが", "film"],
		["毎朝", "まいあさ", "setiap pagi"],
		["毎晩", "まいばん", "setiap malam"],
		["毎日", "まいにち", "setiap hari"],
		["月曜日", "げつようび", "hari Senin"],
		["火曜日", "かようび", "hari Selasa"],
		["水曜日", "すいようび", "hari Rabu"],
		["木曜日", "もくようび", "hari Kamis"],
		["金曜日", "きんようび", "hari Jumat"],
		["土曜日", "どようび", "hari Sabtu"],
		["日曜日", "にちようび", "hari Minggu"],
		["何曜日", "なんようび", "hari apa"],
		["", "〜から", "dari ~"],
		["", "〜まで", "sampai ~"],
		["", "と", "dan"],
		["番号", "ばんごう", "nomor"],
		["何番", "なんばん", "nomor berapa"],
		["", "そちら", "di situ"],
		["", "ニューヨーク", "New York"],
		["", "ペキン", "Beijing"],
		["", "ロサンゼルス", "Los Angels"],
		["", "ロンドン", "London"],
	],
	bab5: [
		["行きます", "いきます", "pergi"],
		["来ます", "きます", "datang"],
		["帰ります", "かえります", "pulang"],
		["学校", "がっこう", "sekolah"],
		["", "スーパー", "pasar swalayan"],
		["駅", "えき", "stasium"],
		["飛行機", "ひこうき", "pesawa terbang"],
		["船", "ふね", "kapal laut"],
		["電車", "でんしゃ", "kereta rel listrik"],
		["地下鉄", "ちかてつ", "kereta bawah tanah"],
		["新幹線", "しんかんせん", "Shinkansen"],
		["", "バス", "bus"],
		["", "タクシー", "taksi"],
		["自転車", "じてんしゃ", "sepeda"],
		["歩いて", "あるいて", "dengan berjalan kaki"],
		["人", "ひと", "orang"],
		["友達", "ともだち", "teman"],
		["彼", "かれ", "dia, ia (laki-laki)"],
		["彼女", "かのじょ", "dia, ia (perempuan)"],
		["家族", "かぞく", "keluarga"],
		["一人で", "ひとりで", "sendirian, dengan sendiri"],
		["先週", "せんしゅう", "minggu lalu"],
		["今週", "こんしゅう", "minggu ini"],
		["来週", "らいしゅう", "minggu depan"],
		["先月", "せんげつ", "bulan lalu"],
		["今月", "こんげつ", "bulan ini"],
		["来月", "らいげつ", "bulan depan"],
		["去年", "きょねん", "tahun lalu"],
		["今年", "ことし", "tahun ini"],
		["来年", "らいねん", "tahun depan"],
		["年", "〜ねん", "tahun-"],
		["何年", "なんねん", "tahun berapa"],
		["月", "〜がつ", "bulan-"],
		["何月", "なんがつ", "bulan apa"],
		["一日", "ついたち", "tanggal satu"],
		["二日", "ふつか", "tanggal dua, dua hari"],
		["三日", "みっか", "tanggal tiga, tiga hari"],
		["四日", "よっか", "tanggal empat, empat hari"],
		["五日", "いつか", "tanggla lima, lima hari"],
		["六日", "むいか", "tanggal enam, enam hari"],
		["七日", "なのか", "tanggal tujuh, tujuh hari"],
		["八日", "ようか", "tanggal delapan, delapan hari"],
		["九日", "ここのか", "tanggal semblian, senblian hari"],
		["十日", "とおか", "tanggal sepuluh, sepuluh hari"],
		["十四日", "じゅうよっか", "tanggal empat belas, empat beras hari"],
		["二十日", "はつか", "tanggal dua puluh, dua puluh hari"],
		[
			"二十四日",
			"にじゅうよっか",
			"tanggal dua puluh empat, dua puluh empat hari",
		],
		["日", "〜にち", "tanggal-, -hari"],
		["何日", "なんにち", "tanggal berapa, berapa hari"],
		["", "いつ", "kepan"],
		["誕生日", "たんじょうび", "hari ulang tahun"],
		["次の", "つぎの", "yang berikutnya"],
		["普通", "ふつう", "biasa"],
		["急行", "きゅうこう", "ekspres"],
		["特急", "とっきゅう", "supper ekspres"],
	],
	bab6: [
		["食べます", "たべます", "makan"],
		["飲みます", "のみます", "minum"],
		["吸います", "すいます", "mengisap [rokrok], merokok"],
		["見ます", "みます", "melihat, menonton"],
		["聞きます", "ききます", "mendengar"],
		["読みます", "よみます", "membaca"],
		["書きます", "かきます", "menulis, menggambar"],
		["買います", "かいます", "membeli"],
		["撮ります", "とります", "mengambil [foto]"],
		["", "します", "mengerjakan, melakukan, berbuat"],
		["会います", "あいます", "bertemu [dengan teman]"],
		["", "ごはん", "nasi"],
		["朝ごはん", "あさごはん", "sarapan"],
		["昼ごはん", "ひるごはん", "makan siang"],
		["晩ごはん", "ばんごはん", "makan malam"],
		["", "パン", "roti"],
		["", "たまご", "telur"],
		["肉", "にく", "daging"],
		["魚", "さかな", "ikan"],
		["野菜", "やさい", "sayur"],
		["果物", "くだもの", "buah-buahan"],
		["水", "みず", "air"],
		["お茶", "おちゃ", "teh, teh Jepang"],
		["紅茶", "こうちゃ", "teh"],
		["牛乳", "ぎゅうにゅう", "susu"],
		["", "ジュース", "jus, sari buah"],
		["", "ビール", "bir"],
		["お酒", "おさけ", "minuman keras"],
		["", "たばこ", "rokok"],
		["手紙", "てがみ", "surat"],
		["", "レポート", "laporan"],
		["写真", "しゃしん", "foto"],
		["", "ビデオ", "keset video, VHS"],
		["店", "みせ", "toko"],
		["庭", "にわ", "halaman"],
		["宿題", "しゅくだい", "pekejaan rumah, PR"],
		["", "テニス", "tenis"],
		["", "サッカー", "sepak bola"],
		["お花見", "おはなみ", "Ohanami, menikmati bunga Sakura"],
		["何", "なに", "apa"],
		["", "いっしょに", "bersama-sama"],
		["", "ちょっと", "sebentar, sedikit"],
		["", "いつも", "selalu"],
		["時々", "ときどき", "kadang-kadang"],
		["", "それから", "setelah itu, kemudian"],
		["", "メキシコ", "Meksiko"],
	],
	bab7: [
		["切ります", "きります", "memotong, mengguniting"],
		["送ります", "おくります", "mengirim"],
		["", "あげます", "memberikan"],
		["", "もらいます", "mandapatkan, menerima"],
		["貸します", "かします", "meminjamkan, menyewakan"],
		["借ります", "かります", "meminjam, menyewa"],
		["教えます", "おしえます", "mengajar"],
		["習います", "ならいます", "belajar"],
		["", "かけます", "menelepon"],
		["手", "て", "tangan"],
		["", "はし", "sumpit"],
		["", "スプーン", "sendok"],
		["", "ナイフ", "pisau"],
		["", "フォーク", "garpu"],
		["", "はさみ", "gunting"],
		["", "パソコン", "komputer, PC"],
		["", "ケータイ", "HP"],
		["", "メール", "e-mail"],
		["年賀状", "ねんがじょう", "kartu tahun baru"],
		["", "パンチ", "pelubang kertas"],
		["", "ホッチキス", "staplar"],
		["", "セロテープ", "selotip"],
		["消しゴム", "けしごむ", "penghapus karet"],
		["紙", "かみ", "kertas"],
		["花", "はな", "bunga"],
		["", "シャツ", "kemeja"],
		["", "プレゼント", "kado, hadiah"],
		["荷物", "にもつ", "barang"],
		["お金", "おかね", "uang"],
		["切符", "きっぷ", "karcis"],
		["", "クリスマス", "Natal"],
		["父", "ちち", "bapak, ayah"],
		["母", "はは", "ibu"],
		["お父さん", "おとうさん", "bapak, ayah"],
		["お母さん", "おかあさん", "ibu"],
		["", "もう", "sudah"],
		["", "まだ", "belum"],
		["", "これから", "mulai dari sekarang"],
		["", "スペイン", "Spanyol"],
	],
	bab8: [
		["", "ハンサムな", "tampan, gagah, ganteng"],
		["綺麗な", "きれいな", "cantik, bersih"],
		["静かな", "しずかな", "sunyi, tenang"],
		["", "にぎやかな", "ramai"],
		["有名な", "ゆうめいな", "terkanal"],
		[
			"親切な",
			"しんせつな",
			"baik hati\n(tidak digunakan untuk keluarga sendiri)",
		],
		["元気な", "げんきな", "sehat walafiat"],
		["暇な", "ひまな", "senggang"],
		["便利な", "べんりな", "praktis"],
		["素敵な", "すてきな", "bagus"],
		["大きい", "おおきい", "besar"],
		["小さい", "ちいさい", "kecil"],
		["新しい", "あたらしい", "baru"],
		["古い", "ふるい", "lama, tua"],
		["良い", "いい / よい", "baik, bagus"],
		["悪い", "わるい", "buruk, jelek"],
		["熱い/暑い", "あつい", "panas"],
		["寒い", "さむい", "dingin\n(mengungkapkan tentang suhu udra)"],
		["冷たい", "つめたい", "dingin\n(mengungkapkan tentang rasa benda)"],
		["難しい", "むずかしい", "sulit, susah"],
		["", "やさしい", "mudah, gampang"],
		["高い", "たかい", "mahal, tinggi"],
		["安い", "やすい", "murah"],
		["低い", "ひくい", "rendah"],
		["面白い", "おもしろい", "menarik"],
		["美味しい", "おいしい", "enak"],
		["忙しい", "いそがしい", "sibuk"],
		["楽しい", "たのしい", "senang"],
		["白い", "しろい", "putih"],
		["黒い", "くろい", "hitam"],
		["赤い", "あかい", "merah"],
		["青い", "あおい", "biru"],
		["桜", "さくら", "Sakura"],
		["山", "やま", "gunung"],
		["町", "まち", "kota"],
		["食べ物", "たべもの", "makanan"],
		["所", "ところ", "tempat"],
		["寮", "りょう", "asrama"],
		["", "レストラン", "restoran"],
		["生活", "せいかつ", "kehidupan"],
		["仕事", "しごと", "pekerjaan"],
		["", "どう", "bagaimana"],
		["", "どんな〜", "yang bagaimana"],
		["", "とても", "sengat, ~sekali"],
		["", "あまり", "kurang begitu ~, tidak begitu ~"],
		["", "そして", "kemudian, dan (digunakan untuk menyambung kalimat)"],
		["", "〜が、〜", "~, tetapi ~"],
		["上海", "シャンハイ", "Shanghai"],
	],
	bab9: [
		["", "わかります", "mengerti"],
		["", "あります", "ada, mempunyai"],
		["好きな", "すきな", "suka, gemar"],
		["嫌いな", "きらいな", "tidak suka"],
		["上手な", "じょうずな", "pandai, pintar"],
		["下手な", "へたな", "tidak pandai, tidak pintar"],
		["飲み物", "のみもの", "minuman"],
		["料理", "りょうり", "masakan"],
		["", "スポーツ", "olahrana"],
		["野球", "やきゅう", "baseball"],
		["", "ダンス", "dansa"],
		["旅行", "りょこう", "tamasya"],
		["音楽", "おんがく", "musik"],
		["歌", "うた", "lagu"],
		["", "クラシック", "klasik"],
		["", "ジャズ", "jaz"],
		["", "コンサート", "konser"],
		["", "カラオケ", "karaoke"],
		["歌舞伎", "かぶき", "Kabuki"],
		["絵", "え", "gambar"],
		["字", "じ", "huruf"],
		["漢字", "かんじ", "Kanji"],
		["", "ひらがな", "Hiragana"],
		["", "カタカナ", "Katakana"],
		["ローマ字", "ローマじ", "huruf latin"],
		["細かいお金", "こまかいおかね", "uang kecil, receh"],
		["", "チケット", "tiket"],
		["時間", "じかん", "jam, waktu"],
		["用事", "ようじ", "urusan"],
		["約束", "やくそく", "janji"],
		["", "アルバイト", "kerja paruh waktu"],
		[
			"ご主人",
			"ごしゅじん",
			"suami (digunakan untuk\nmenyebutkan suami orang lain)",
		],
		[
			"夫 / 主人",
			"おっと / しゅじん",
			"suami (digunakan untuk\nmenyebutkan istri orang latin)",
		],
		[
			"奥さん",
			"おくさん",
			"istri (digunakan untuk\nmenyebutkan istri orang lain)",
		],
		["妻 / 家内", "つま / かない", "istri"],
		["子供", "こども", "anak"],
		["", "よく", "dengan baik"],
		["大体", "だいたい", "kira-kira"],
		["沢山", "たくさん", "banyak"],
		["少し", "すこし", "sedikit"],
		["全然", "ぜんぜん", "sama sekali (diikuti kalimat negatif)"],
		["速く / 早く", "はやく", "dengat cepat"],
		["", "〜から", "karena ~, sebab ~"],
		["", "どうして", "kenapa"],
	],
	bab10: [
		["", "あります", "ada (digunakan untuk benda mati)"],
		["", "います", "ada (digunakan untuk makhluk hidup)"],
		["色々な", "いろいろな", "berbagai"],
		["男の人", "おとこのひと", "orang laki-laki"],
		["女の人", "おんなのひと", "orang perempuan"],
		["男の子", "おとこのこ", "anak laki-laki"],
		["女の子", "おんなのこ", "anak perempuan"],
		["犬", "いぬ", "anjing"],
		["猫", "ねこ", "kucing"],
		["", "パンダ", "panda"],
		["象", "ぞう", "gajah"],
		["木", "き", "pohon"],
		["物", "もの", "barang"],
		["電池", "でんち", "beterai"],
		["箱", "はこ", "kotak"],
		["", "スイッチ", "tombol, sakelar"],
		["冷蔵庫", "れいぞうこ", "kulkas, lemari es"],
		["", "テーブル", "meja makan"],
		["", "ベッド", "tempat tidur"],
		["棚", "たな", "lemari"],
		["", "ドア", "pintu"],
		["窓", "まど", "jendela"],
		["", "ポスト", "kotak surat"],
		["", "ビル", "gedung"],
		["", "ATM, エーティーエム", "ATM"],
		["", "コンビニ", "toko 24 jam"],
		["公園", "こうえん", "taman"],
		["喫茶店", "きっさてん", "coffee shop"],
		["屋", "〜や", "toko ~"],
		["乗り場", "のりば", "tempat naik"],
		["県", "けん", "prefekture"],
		["上", "うえ", "atas"],
		["下", "した", "bawah"],
		["前", "まえ", "depan, muka"],
		["後ろ", "うしろ", "belakang"],
		["右", "みぎ", "kanan"],
		["左", "ひだり", "kiri"],
		["中", "なか", "dalam"],
		["外", "そと", "luar"],
		["隣", "となり", "sebelah"],
		["近く", "ちかく", "dekat"],
		["間", "あいだ", "antara"],
		["", "〜や〜など", "~ dan ~ [dan lain-lain]"],
	],
	bab11: [
		["漢字", "見出し語", "インドネシア語"],
		["", "います", "ada, mempunyai [anak]"],
		["", "かかります", "memakan, perlu (digunakan untuk waktu dan uang)"],
		["休みます", "やすみます", "tidak masuk [kerja]"],
		["", "ひとつ", "satu"],
		["", "ふたつ", "dua"],
		["", "みっつ", "tiga"],
		["", "よっつ", "empat"],
		["", "いつつ", "lima"],
		["", "むっつ", "enam"],
		["", "ななつ", "tujuh"],
		["", "やっつ", "delapan"],
		["", "ここのつ", "sembilan"],
		["", "とお", "sepukuh"],
		["", "いくつ", "berapa"],
		["", "ひとり", "seorang"],
		["", "ふたり", "dua orang"],
		["〜人", "にん", "~ orang"],
		[
			"〜台",
			"だい",
			"buah (kata bantu bilangan yang digunakan untuk menghitung mesin dan mobil)",
		],
		[
			"〜枚",
			"まい",
			"lembar, helai (kata bantu bilangan yang digunakan untuk menghitung kertas dan perangko)",
		],
		["〜回", "かい", "~ kali"],
		["", "りんご", "apel"],
		["", "みかん", "jeruk mandarin"],
		["", "サンドイッチ", "sandwich"],
		["", "カレー, カレーライス", "[nasi dan] kare"],
		["", "アイスクリーム", "es krim"],
		["切手", "きって", "perangko"],
		["", "はがき", "kartu pos"],
		["封筒", "ふうとう", "amplop"],
		["両親", "りょうしん", "orang tua"],
		["兄弟", "きょうだい", "saudara, saudari"],
		["兄", "あに", "kakak laki-laki\n(untuk menyebutkan kakak sendiri)"],
		[
			"お兄さん",
			"おにいさん",
			"kakak laki-laki\n(untuk menyebutkan\nkakak laki-laki orang lain)",
		],
		["姉", "あね", "kakak perempuan\n(untuk menyebutkan kakak sendiri)"],
		[
			"お姉さん",
			"おねえさん",
			"kakak perempuan\n(untuk menyebutkan\nkakak perempuan orang lain)",
		],
		["弟", "おとうと", "adik laki-laki\n(untuk menyebutkan adik sendiri)"],
		[
			"弟さん",
			"おとうとさん",
			"adik laki-laki\n(untuk menyebutkan\nadik laki-laki orang lain)",
		],
		["妹", "いもうと", "adik perempuan\n(untuk menyebutkan adik sendiri)"],
		[
			"妹さん",
			"いもうとさん",
			"adik perempuan\n(untuk menyebutkan\nadik perempuan orang lain)",
		],
		["外国", "がいこく", "luar negeri"],
		["留学生", "りゅうがくせい", "pelajar asing"],
		["", "クラス", "kelas"],
		["〜時間", "じかん", "~ jam"],
		["〜週間", "しゅうかん", "~ minggu"],
		["〜か月", "かげつ", "~ bulan"],
		["〜年", "ねん", "~ tahun"],
		["", "ぐらい, くらい", "kira-kira ~"],
		["", "どのくらい", "berapa lama"],
		["全部で", "ぜんぶで", "semuanya"],
		["", "みんな", "semua"],
		["", "だけ", "hanya~, ~ saja"],
	],
	bab12: [
		["漢字", "見出し語", "インドネシア語"],
		["簡単な", "かんたんな", "mudah, gampang"],
		["近い", "ちかい", "dekat"],
		["遠い", "とおい", "jauh"],
		["早い/速い", "はやい", "cepat"],
		["遅い", "おそい", "lambat"],
		["多い", "おおい", "banyak"],
		["少ない", "すくない", "sedikit"],
		["暖かい/温かい", "あたたかい", "hangat"],
		["涼しい", "すずしい", "sejuk"],
		["甘い", "あまい", "manis"],
		["辛い", "からい", "oedas"],
		["重い", "おもい", "berat"],
		["軽い", "かるい", "ringan"],
		["良い", "よい/いい", "lebih baik"],
		["季節", "きせつ", "musim"],
		["春", "はる", "musim semi"],
		["夏", "なつ", "musim panas"],
		["秋", "あき", "musim gugur"],
		["冬", "ふゆ", "musim dingin"],
		["天気", "てんき", "cuaca"],
		["雨", "あめ", "hujan"],
		["雪", "ゆき", "salju"],
		["曇り", "くもり", "mendung"],
		["", "ホテル", "hotel"],
		["空港", "くうこう", "bandara"],
		["海", "うみ", "laut"],
		["世界", "せかい", "dunia"],
		["", "パーティー", "pesta"],
		["お祭り", "おまつり", "perayaan"],
		[
			"すき焼き",
			"すきやき",
			"Sukiyaki (masakan yang dimasak daging sapi dan sayur dalam panic)",
		],
		["", "さしみ", "Sashimi (ikan mentah yang dipotong tipis)"],
		[
			"",
			"おすし",
			"Sushi (nasi dicampur cuka yang di atasnya diberi ikan mentah)",
		],
		[
			"",
			"てんぷら",
			"Tempura (gorengan sari laut dan sayur yang dipakai tepung terigu)",
		],
		["豚肉", "ぶたにく", "daging babi"],
		["鶏肉", "とりにく", "daging ayam"],
		["牛肉", "ぎゅうにく", "daging sapi"],
		["", "レモン", "lemon"],
		["生け花", "いけばな", "seni merangkai bunga"],
		["紅葉", "もみじ", "maple (daun yang berubah warna menjadi merah)"],
		["", "どちら", "yang mana"],
		["", "どちらも", "dua-duanya, yang mana juga"],
		["一番", "いちばん", "paling"],
		["", "ずっと", "jauh lebih"],
		["初めて", "はじめて", "untuk pertama kali"],
		["香港", "ほんこん", "Hong Kong"],
		["", "シンガポール", "Singapura"],
	],
	bab13: [
		["遊びます", "あそびます", "bermain"],
		["泳ぎます", "およぎます", "berenang"],
		["迎えます", "むかえます", "menjemput"],
		[
			"疲れます",
			"つかれます",
			"lelah (jika menyatakan keadaan lelah, digunakan bentuk た seperti つかれました)",
		],
		["結婚します", "けっこんします", "menikah"],
		["買い物します", "かいものします", "berbelanja"],
		["食事します", "しょくじします", "makan"],
		["散歩します", "さんぽします", "berjalan-jalan"],
		["大変な", "たいへんな", "berat, susah"],
		["欲しい", "ほしい", "ingin, mau"],
		["広い", "ひろい", "luas"],
		["狭い", "せまい", "sempit"],
		["プール", "プール", "kolam renang"],
		["川", "かわ", "sungai"],
		["美術", "びじゅつ", "seni"],
		["釣り", "つり", "pancing (〜をします: memancing)"],
		["スキー", "スキー", "ski (〜をします: bermain ski)"],
		["週末", "しゅうまつ", "akhir pekan"],
		["お正月", "おしょうがつ", "tahun baru"],
		["", "ごろ", "sekitar~, kira-kira"],
		["何か", "なにか", "sesuatu"],
		["", "どこか", "suatu tempat"],
		["定食", "ていしょく", "menu paket"],
		["別々に", "べつべつに", "sendiri-sendiri, masing-masing"],
	],
	bab14: [
		["", "つけます", "menyalakan"],
		["消します", "けします", "mematikan"],
		["開けます", "あけます", "membuka"],
		["閉めます", "しめます", "menutup"],
		["急ぎます", "いそぎます", "buru-buru"],
		["待ちます", "まちます", "menunggu"],
		["持ちます", "もちます", "membawa"],
		["取ります", "とります", "mengambil"],
		["手伝います", "てつだいます", "membantu"],
		["呼びます", "よびます", "memanggil"],
		["話します", "はなします", "berbicara"],
		["使います", "つかいます", "memakai"],
		["止めます", "とめます", "menghentikan"],
		["見せます", "みせます", "memperlihatkan"],
		["教えます", "おしえます", "memberitahukan"],
		["座ります", "すわります", "duduk"],
		["立ちます", "たちます", "berdiri"],
		["入ります", "はいります", "masuk"],
		["出ます", "でます", "keluar"],
		["降ります", "ふります", "turun"],
		["", "コピーします", "memfotokopi"],
		["電気", "でんき", "listrik"],
		["", "エアコン", "AC"],
		["", "パスポート", "paspor"],
		["名前", "なまえ", "nama"],
		["住所", "じゅうしょ", "alamat"],
		["地図", "ちず", "peta"],
		["塩", "しお", "garam"],
		["砂糖", "さとう", "gula"],
		["問題", "もんだい", "masalah"],
		["答え", "こたえ", "jawaban"],
		["読み方", "よみかた", "cara membaca"],
		["〜方", "かた", "cara ~"],
		["", "まっすぐ", "lurus"],
		["", "ゆっくり", "pelan-pelan"],
		["", "すぐ", "segera"],
		["", "また", "lagi"],
		["後で", "あとで", "nanti"],
		["", "もうすこし", "sedikit lagi"],
		["", "もう〜", "~ lagi"],
		["", "さあ", "mari"],
		["", "あれ？", "Ah?"],
		["お釣り", "おつり", "uang kembalian"],
	],
	bab15: [
		["置きます", "おきます", "meletakkan"],
		["作ります", "つくります", "membuat"],
		["売ります", "うります", "menjual"],
		["知ります", "しります", "mengetahui"],
		["住みます", "すみます", "tinggal"],
		["研究します", "けんきゅうします", "meneliti"],
		["資料", "しりょう", "data"],
		["", "カタログ", "katalog"],
		["時刻表", "じこくひょう", "jadwal"],
		["服", "ふく", "baju"],
		["製品", "せいひん", "produk"],
		["電子辞書", "でんしじしょ", "kamus elektronik"],
		["経済", "けいざい", "ekonomi"],
		["市役所", "しやくしょ", "kantor wali kota"],
		["高校", "こうこう", "SMA"],
		["歯医者", "はいしゃ", "dokter gigi"],
		["独身", "どくしん", "bujangan"],
		["", "すみません", "Maaf."],
		["皆さん", "みなさん", "semuanya"],
		["思い出します", "おもいだします", "teringat"],
		["", "いらっしゃいます", "bentuk hormat dari います"],
	],
	bab16: [
		["乗ります", "のります", "naik"],
		["降ります", "おります", "turun"],
		["乗り換えます", "のりかえます", "ganti"],
		["浴びます", "あびます", "mandi"],
		["入れます", "いれます", "memasukkan"],
		["出します", "だします", "mengeluarkan"],
		["下ろします", "おろします", "mengeluarkan"],
		["入ります", "はいります", "masuk"],
		["出ます", "でます", "tamat"],
		["押します", "おします", "menekan"],
		["飲みます", "のみます", "minum"],
		["始めます", "はじめます", "mulai"],
		["見学します", "けんがくします", "mengunjungi"],
		["電話します", "でんわします", "menelepon"],
		["若い", "わかい", "muda"],
		["長い", "ながい", "panjang"],
		["短い", "みじかい", "pendek"],
		["明るい", "あかるい", "terang"],
		["暗い", "くらい", "gelap"],
		["体", "からだ", "badan"],
		["頭", "あたま", "kepala"],
		["髪", "かみ", "rambut"],
		["顔", "かお", "muka"],
		["目", "め", "mata"],
		["耳", "みみ", "telinga"],
		["鼻", "はな", "hidung"],
		["口", "くち", "mulut"],
		["歯", "は", "gigi"],
		["", "おなか", "perut"],
		["足", "あし", "kaki"],
		["背", "せ", "punggung"],
		["", "サービス", "pelayanan"],
		["", "ジョギング", "joging"],
		["", "シャワー", "shower"],
		["緑", "みどり", "hijau"],
		["お寺", "おてら", "wihara"],
		["神社", "じんじゃ", "kuil Shinto"],
		["〜番", "ばん", "nomor ~"],
		["", "どうやって", "dengan cara bagaimana"],
		["", "どの〜", "~ yang mana"],
		["", "どれ", "mana"],
		["", "まず", "pertama-tama"],
		["次に", "つぎに", "kemudian"],
		["", "キャッシュカード", "kartu ATM"],
		["暗証番号", "あんしょうばんごう", "PIN"],
		["金額", "きんがく", "jumlah uang"],
		["確認", "かくにん", "cek"],
		["", "ボタン", "tombol"],
	],
	bab17: [
		["覚えます", "おぼえます", "mengingat"],
		["忘れます", "わすれます", "lupa"],
		["", "なくします", "kehilangan"],
		["払います", "はらいます", "membayar"],
		["返します", "かえします", "mengembalikan"],
		["出かけます", "でかけます", "pergi"],
		["脱ぎます", "ぬぎます", "buka"],
		["持って行きます", "もっていきます", "membawa pergi"],
		["持って来ます", "もってきます", "membawa datang"],
		["心配します", "しんぱいします", "mengkhawatirikan"],
		["残業します", "ざんぎょうします", "melembur"],
		["出張します", "しゅっちょうします", "dinas"],
		["飲みます", "のみます", "minum"],
		["入ります", "はいります", "mandi"],
		["大切な", "たいせつな", "penting"],
		["大丈夫な", "だいじょうぶな", "tidak apa-apa"],
		["危ない", "あぶない", "berbahaya"],
		["禁煙", "きんえん", "dilarang merokok"],
		["健康保険証", "けんこうほけんしょう", "katru asuransi kesehatan"],
		["熱", "ねつ", "demam"],
		["病気", "びょうき", "sakit"],
		["薬", "くすり", "obat"],
		["", "おふろ", "mandi"],
		["上着", "うわぎ", "baju"],
		["下着", "したぎ", "pakaian dalam"],
		["２、３日", "２、３にち", "dua atau tiga hari"],
		["", "〜までに", "sampai dengan"],
		["", "ですから", "oleh karena itu"],
		["", "のど", "kerongkongan"],
		["", "かぜ", "masuk angin"],
		["", "それから", "dan"],
	],
	bab18: [
		["", "できます", "dapat"],
		["洗います", "あらいます", "mencuci"],
		["弾きます", "ひきます", "bermain"],
		["歌います", "うたいます", "bernyanyi"],
		["集めます", "あつめます", "mengumpulkan"],
		["捨てます", "すてます", "membuang"],
		["換えます", "かえます", "mengganti"],
		["運転します", "うんてんします", "menyatir"],
		["予約します", "よやくします", "memesan"],
		["", "ピアノ", "piano"],
		["", "〜メートル", "~ meter"],
		["現金", "げんきん", "uang tunai"],
		["趣味", "しゅみ", "hobi"],
		["日記", "にっき", "catatan harian"],
		["お祈り", "おいのり", "doa"],
		["課長", "かちょう", "kepala seksi"],
		["部長", "ぶちょう", "kepala bagian"],
		["社長", "しゃちょう", "direktur utama"],
		["動物", "どうぶつ", "hewan"],
		["馬", "うま", "kuda"],
		["", "インターネット", "internet"],
		["特に", "とくに", "terutama"],
		["", "へえ", "Betul ya?"],
		["", "なかなか", "jarang"],
		["", "ぜひ", "benar-benar"],
		["故郷", "ふるさと", "Furusato"],
	],
	bab19: [
		["登ります", "のぼります", "naik"],
		["泊まります", "とまります", "menginap"],
		["掃除します", "そうじします", "membersihkan"],
		["洗濯します", "せんたくします", "mencuci pakaian"],
		["眠い", "ねむい", "mengantuk"],
		["強い", "つよい", "kuat"],
		["弱い", "よわい", "lemah"],
		["練習", "れんしゅう", "latihan"],
		["", "ゴルフ", "golf"],
		["相撲", "すもう", "sumo"],
		["お茶", "おちゃ", "upacara minum teh"],
		["日", "ひ", "hari"],
		["調子", "ちょうし", "kondisi"],
		["一度", "いちど", "sekali"],
		["一度も", "いちども", "sekali-kali"],
		["", "だんだん", "berangsur-angsuran"],
		["", "もうすぐ", "tidak lama lagi"],
		["", "おかげさまで", "atas berkat"],
		["", "でも", "tetap"],
		["乾杯", "かんぱい", "toast"],
		["", "ダイエット", "diet"],
		["無理な", "むりな", "paksa"],
		["体にいい", "からだにいい", "baik untuk tubuh"],
	],
	bab20: [
		["要ります", "いります", "memerlukan"],
		["調べます", "しらべます", "memeriksa"],
		["修理します", "しゅうりします", "memperbaiki"],
		["僕", "ぼく", "aku"],
		["君", "きみ", "kamu"],
		["〜君", "くん", "Sdr.~"],
		["", "うん", "ya"],
		["", "ううん", "tidak"],
		["", "ことば", "kata"],
		["着物", "きもの", "kimono"],
		["", "ビザ", "VISA"],
		["初め", "はじめ", "awal"],
		["終わり", "おわり", "akhir"],
		["", "こっち", "sini"],
		["", "そっち", "situ"],
		["", "あっち", "sana"],
		["", "どっち", "mana"],
		["", "みんなで", "kita semua"],
		["", "〜けど", "~ tetapi"],
		["", "よかったら", "kalau mau"],
		["", "いろいろ", "macam-macam"],
	],
	bab21: [
		["思います", "おもいます", "mengira"],
		["言います", "いいます", "mengatakan"],
		["勝ちます", "かちます", "menang"],
		["負けます", "まけます", "kalah"],
		["", "あります", "ada"],
		["役に立ちます", "やくにたちます", "berguna"],
		["動きます", "うごきます", "pindah"],
		["", "やめます", "berhenti"],
		["気をつけます", "きをつけます", "berwaspada"],
		["留学します", "りゅうがくします", "studi di luar negeri"],
		["", "むだな", "sia-sia"],
		["不便な", "ふべんな", "tidak ptaktis"],
		["", "すごい", "hebat"],
		["", "ほんとう", "betul"],
		["", "うそ", "bohong"],
		["自動車", "じどうしゃ", "mobil"],
		["交通", "こうつう", "lalu lintas"],
		["物価", "ぶっか", "harga barang"],
		["放送", "ほうそう", "siaran"],
		["", "ニュース", "warta berita"],
		["", "アニメ", "animasi"],
		["", "マンガ", "manga"],
		["", "デザイン", "desain"],
		["夢", "ゆめ", "mimpi"],
		["天才", "てんさい", "genius"],
		["試合", "しあい", "pertandingan"],
		["意見", "いけん", "pendapat"],
		["話", "はなし", "cerita"],
		["地球", "ちきゅう", "bumi"],
		["月", "つき", "bulan"],
		["最近", "さいきん", "akhir-akhir ini"],
		["", "たぶん", "mungkin"],
		["", "きっと", "pasti"],
		["", "ほんとうに", "betul-betul"],
		["", "そんなに", "tidak begitu"],
		["", "〜について", "tentang ~"],
	],
	bab22: [
		["着ます", "きます", "memakai"],
		["", "はきます", "memakai"],
		["", "かぶります", "memakai"],
		["", "かけます", "memakai"],
		["", "します", "memakai"],
		["生まれます", "うまれます", "lahir"],
		["", "わたしたち", "kami"],
		["", "コート", "mantal"],
		["", "セーター", "sweater"],
		["", "スーツ", "pakaisan setelan"],
		["帽子", "ぼうし", "topi"],
		["眼鏡", "めがね", "kaca mata"],
		["", "ケーキ", "kue"],
		["お弁当", "おべんとう", "bekal"],
		["", "ロボット", "robot"],
		["", "ユーモア", "humor"],
		["都合", "つごう", "kondisi"],
		["", "よく", "sering kali"],
		["", "えーと", "Itu…"],
		["", "おめでとうございます", "Selamat."],
		["", "では", "kalau begitu"],
		["", "こちら", "ini"],
		["家賃", "やちん", "biaya sewa rumah"],
		["和室", "わしつ", "kamar ala Jepang"],
		["押入れ", "おしいれ", "lemari dinding ala Jepang"],
		["布団", "ふとん", "selimut dan kasur berisi kapas ala Jepang"],
	],
	bab23: [
		["聞きます", "ききます", "bertanya"],
		["回します", "まわします", "memutar"],
		["引きます", "ひきます", "tarik"],
		["変えます", "かえます", "mengubah"],
		["触ります", "さわります", "menyantuh"],
		["出ます", "でます", "keluar"],
		["歩きます", "あるきます", "berjalan kaki"],
		["渡ります", "わたります", "menyaberang"],
		["曲がります", "まがります", "belok"],
		["寂しい", "さびしい", "sepi"],
		["お湯", "おゆ", "air panas"],
		["音", "おと", "bunyi"],
		["", "サイズ", "ukuran"],
		["故障", "こしょう", "kerusakan"],
		["道", "みち", "jalan"],
		["交差点", "こうさてん", "perempatan"],
		["信号", "しんごう", "lampu lalu lintas"],
		["角", "かど", "sudut"],
		["橋", "はし", "jembatan"],
		["駐車場", "ちゅうしゃじょう", "tempat parkir"],
		["建物", "たてもの", "gedung"],
		["何回も", "なんかいも", "berkali-kali"],
		["〜目", "め", "yang ke ~"],
	],
	bab24: [
		["", "くれます", "diberikan"],
		["直します", "なおします", "mengoreksi"],
		["連れて行きます", "つれていきます", "membawa"],
		["連れて来ます", "つれてきます", "membawa"],
		["送ります", "おくります", "mengantar"],
		["紹介します", "しょうかいします", "memperkenalkan"],
		["案内します", "あんないします", "mengantarkan"],
		["説明します", "せつめいします", "menjelaskan"],
		["", "おじいさん", "kekek"],
		["", "おばあさん", "nenek"],
		["準備", "じゅんび", "persiapan"],
		["引っ越し", "ひっこし", "pindah rumah"],
		["お菓子", "おかし", "kue"],
		["", "ホームステイ", "homestay"],
		["全部", "ぜんぶ", "semua"],
		["自分で", "じぶんで", "dengan sendiri"],
		["", "ほかに", "selain"],
	],
	bab25: [
		["考えます", "かんがえます", "berpikir"],
		["着きます", "つきます", "tiba"],
		["取ります", "とります", "berumur"],
		["足ります", "たります", "cukup"],
		["田舎", "いなか", "desa"],
		["", "チャンス", "kesempatan"],
		["億", "おく", "ratus jata"],
		["", "もし〜たら", "kalau"],
		["意味", "いみ", "arti"],
		["", "もしもし", "halo"],
		["転勤", "てんきん", "pinkah ke kantor cabang lain atau jabatan lain"],
		["", "こと", "halo"],
		["暇", "ひま", "waktu luang"],
		["", "頑張ります", "berusaha"],
	],
	bab26: [
		["診る", "みます", "Periksa"],
		["探す", "さがします", "Mencari"],
		["遅れる", "おくれます［じかんに～］", "terlambat [ pertemuan, dll]"],
		[
			"間に合う",
			"まにあいます［じかんに～",
			"Sempat/tepat waktu [pertemuan, dll]",
		],
		["遣る", "やります", "Melakukan"],
		["参加する", "さんかします［パーティーに］", "Partisipasi, menghadiri"],
		["申し込む", "もうしこみます", "Mendaftarkan diri"],
		["都合がいい", "つごうがいい", "nyaman (mengenai waktu)"],
		["都合が悪い", "つごうがわるい", "Tidak nyaman (mengenai waktu)"],
		["気分がいい", "きぶんがいい", "Perasaan enak"],
		["気分が悪い", "きぶんがわるい", "Perasaan kurang baik"],
		[
			"新聞社",
			"しんぶんしゃ",
			"koran perusahaan penerbitan, kantor surat kabar",
		],
		["柔道", "じゅうどう", "Judo"],
		["運動会", "うんどうかい", "Festival olahraga"],
		["場所", "ばしょ", "Tempat"],
		["ボランティア", "ボランティア", "Sukarelawan"],
		["～弁", "～べん", "Dialek / logat"],
		["今度", "こんど", "kali, lain waktu"],
		["ずいぶん", "ずいぶん", "Cukup/ lumayan"],
		["直接", "ちょくせつ", "Langsung"],
		["いつでも", "いつでも", "setiap saat/ kapanpun"],
		["どこでも", "どこでも", "Dimanapun"],
		["だれでも", "だれでも", "siapa saja"],
		["何でも", "なんでも", "apa pun"],
		["こんな～", "こんな～", "~ Seperti ini"],
		["そんな～", "そんな～", "~ Seperti itu (dekat pendengar)"],
		[
			"あんな～",
			"あんな～",
			"~ Seperti itu (jauh dari kedua pembicara dan pendengar)",
		],
		["方づく", "かたづきます［にもつが～］", "Merapihkan ( barang )"],
		["ごみ", "ごみ", "Sampah"],
		["出す", "だします［ごみを～］", "Mengeluarkan/ membuang [sampah]"],
		["燃える", "もえます［ごみが～］", "[Sampah] bisa dibakar"],
		["月・水・金", "げつ・すい・きん", "Senin, Rabu dan Jumat"],
		["置き場", "おきば", "tempat menyimpan/ meletakan sesuatu"],
		["横", "よこ", "Sisi/ samping"],
		["瓶", "びん", "Botol kaca"],
		["缶", "かん", "Kaleng"],
		["［お］湯", "おゆ", "air panas"],
		["ガス", "ガス", "Gas"],
		["～会社", "～かいしゃ", "~ perusahaan"],
		["連絡する", "れんらくします", "Laporan/ menghubungi"],
		[
			"困ったなあ",
			"こまったなあ",
			"Sulit! (ekspresi)Apa yang harus saya lakukan?",
		],
		["読み物", "よみもの", "Bacaan"],
		["電子メール", "でんしメール", "Surat elektronik"],
		["宇宙", "うちゅう", "Ruang Angkasa"],
		["怖い", "こわい", "Takut"],
		["宇宙船", "うちゅうせん", "kapal angkasa"],
		["別の", "べつの", "Lain"],
		["宇宙飛行士", "うちゅうひこうし", "Astronaut"],
	],
	bab27: [
		["飼う", "かいます", "memelihara"],
		["建てる", "たてます", "membangun"],
		["走る", "はしります［みちを～］", "berlari ( ~ dijalan )"],
		["取る", "とります［やすみを～］", "Mengambil ( ~ istirahat )"],
		["見える", "みえます［やまが～］", "Terlihat ( gunung nya ~ )"],
		["聞こえる", "きこえます［おとが～］", "Terdengar ( Suara nya ~ )"],
		[
			"できる",
			"できます［くうこうが～］",
			"Jadi /selesai dibuat ( Bandara nya ~ )",
		],
		["開く", "ひらきます［きょうしつを～］", "Terbuka [~ kelas]"],
		["ペット", "ペット", "( hewan ) peliharaan"],
		["鳥", "とり", "burung"],
		["声", "こえ", "suara ( manusia & binatang )"],
		["波", "なみ", "gelombang"],
		["花火", "はなび", "kembang api"],
		["景色", "けしき", "pemandangan"],
		["昼間", "ひるま", "Siang hari"],
		["昔", "むかし", "masa lalu"],
		["道具", "どうぐ", "alat"],
		["自動販売機", "じどうはんばいき", "mesin penjual otomatis"],
		["通信販売", "つうしんはんばい", "Pesan antar"],
		["クリーニング", "クリーニング", "Laundri"],
		["マンション", "マンション", "Apartemen"],
		["台所", "だいどころ", "dapur"],
		["～教室", "～きょうしつ", "Kelas ~"],
		["パーティールーム", "パーティールーム", "Ruang Pesta"],
		["～後", "～ご", "setelah ~"],
		["～しか", "～しか", "hanya ~"],
		["ほかの", "ほかの", "Lainnya, sebagai tambahan"],
		["はっきり", "はっきり", "jelas"],
		["ほとんど", "ほとんど", "Hampir"],
		["関西空港", "かんさいくうこう", "Bandara Kansai"],
		["秋葉原", "あきはばら", "Akihabara"],
		[
			"日曜大工",
			"にちようだいく",
			"Do It Yourself ( lakukan sendiri dihari minggu )",
		],
		["本棚", "ほんだな", "Rak buku"],
		["夢", "ゆめ", "mimpi"],
		["いつか", "いつか", "suatu saat/waktu"],
		["家", "いえ", "Rumah"],
		["すばらしい", "すばらしい", "Luar biasa/ bagus/ Mantap"],
		["子どもたち", "こどもたち", "anak-anak"],
		["大好き［な］", "だいすき［な］", "Favorit / kesukaan"],
		["漫画", "まんが", "komik"],
		["主人公", "しゅじんこう", "Pemeran utama"],
		["形", "かたち", "bentuk"],
		["ロボット", "ロボット", "robot"],
		["不思議", "ふしぎ", "Misteri, aneh"],
		["ポケット", "ポケット", "Kantong, saku"],
		["例えば", "たとえば", "sebagai contoh, misal"],
		["付ける", "つけます", "mengenakan, mengaitkan, menyalakan"],
		["自由に", "じゆうに", "bebas"],
		["空", "そら", "Langit"],
		["飛ぶ", "とびます", "terbang"],
		["自分", "じぶん", "diri sendiri"],
		["将来", "しょうらい", "masa depan"],
		["ドラえもん", "ドラえもん", "Doraemon"],
	],
	bab28: [
		["売れる", "うれます［パンが～］", "terjual ( rotinya ~ )"],
		["踊る", "おどります", "menari"],
		["噛む", "かみます", "Menguyah, gigit"],
		["選ぶ", "えらびます", "Memilih"],
		["違う", "ちがいます", "Salah, beda"],
		[
			"通う",
			"かよいます［だいがくに～］",
			"Menjalankan aktifitas rutin/pergi - pulang (~ kuliah )",
		],
		["メモする", "メモします", "Buat catatan"],
		["まじめ［な］", "まじめ［な］", "Serius"],
		["熱心［な］", "ねっしん［な］", "Antusias, membara"],
		["優しい", "やさしい", "Ramah, penyayang"],
		["偉い", "えらい", "hebat ( berjiwa besar )"],
		["丁度いい", "ちょうどいい", "pas"],
		["習慣", "しゅうかん", "Kebiasaan"],
		["経験", "けいけん", "pengalaman"],
		["力", "ちから", "Kekuatan, tenaga"],
		["人気", "にんき", "Populer"],
		["形", "かたち", "bentuk"],
		["色", "いろ", "warna"],
		["味", "あじ", "rasa"],
		["ガム", "ガム", "Permen karet"],
		["品物", "しなもの", "barang"],
		["値段", "ねだん", "harga"],
		["給料", "きゅうりょう", "gaji"],
		["ボーナス", "ボーナス", "bonus"],
		["番組", "ばんぐみ", "Acara tv/ program"],
		["ドラマ", "ドラマ", "Drama"],
		["小説", "しょうせつ", "novel"],
		["小説家", "しょうせつか", "Novelis"],
		["歌手", "かしゅ", "penyanyi"],
		["管理人", "かんりにん", "Pengelola"],
		["息子", "むすこ", "Putra/anak laki2 ( anak sendiri )"],
		["息子さん", "むすこさん", "Putra/anak laki2 ( anak orang lain )"],
		["娘", "むすめ", "Putri/ anak perempuan ( anak sendiri)"],
		["娘さん", "むすめさん", "Putri/ anak perempuan ( anak orang lain)"],
		["自分", "じぶん", "Diri sendiri"],
		["将来", "しょうらい", "masa depan"],
		["暫く", "しばらく", "sejenak, sebentar"],
		["大抵", "たいてい", "biasanya"],
		["それに", "それに", "Lagi pula, selain itu, dan juga"],
		["それで", "それで", "dengan begitu"],
		[
			"お願いがあるんです",
			"おねがいが あるんです",
			"( maaf ) sebenarnya, ada sedikit permohonan..",
		],
		["ホームステイ", "ホームステイ", "Rumah singgah"],
		["会話", "かいわ", "percakapan"],
		["お喋りする", "おしゃべりします", "Berkata-kata"],
		["お知らせ", "おしらせ", "Pengumuman, pemberitahuan"],
		["日にち", "ひにち", "tanggal"],
		["土", "ど", "Sabtu"],
		["体育館", "たいいくかん", "Gedung Olah Raga"],
		["無料", "むりょう", "Gratis"],
	],
	bab29: [
		["開く", "あきます［ドアが～］", "Terbuka ( pintunya ~ )"],
		["閉まる", "しまります［ドアが～］", "Tertutup ( pintunya ~ )"],
		["点く", "つきます［でんきが～］", "Menyala ( lampunya ~ )"],
		["消える", "きえます［でんきが～］", "Mati / menghilang ( lampunya ~ )"],
		["込む", "こみます［みちが～］", "Macet ( jalanan ~ )"],
		["空く", "すきます［みちが～］", "Kosong / lancar ( jalanan ~ )"],
		["壊れる", "こわれます［いすが～］", "Rusak ( kursi nya ~ )"],
		["割れる", "われます［カップが～］", "retak/pecah ( gelas nya ~ )"],
		["折れる", "おれます［きが～］", "Patah ( pohon nya ~ )"],
		["破れる", "やぶれます［かみが～］", "robek/sobek ( kertas nya ~ )"],
		["汚れる", "よごれます［ふくが～］", "Ternodai / kotor ( pakaian nya ~ )"],
		["付く", "つきます［ポケットが～］", "terpasang ( katong nya ~ )"],
		["外れる", "はずれます［ボタンが～］", "Lepas /copot ( kancing nya ~ )"],
		["止まる", "とまります［エレベーターが～］", "berhenti"],
		["間違える", "まちがえます", "kesalahan"],
		["落す", "おとします", "Penurunan"],
		["掛かる", "かかります［かぎが～］", "menggantungkan ( mengunci )"],
		["［お］皿", "［お］さら", "Piring"],
		["［お］茶碗", "［お］ちゃわん", "Mangkuk"],
		["コップ", "コップ", "Cangkir"],
		["ガラス", "ガラス", "Kaca"],
		["袋", "ふくろ", "Kantong plastik"],
		["財布", "さいふ", "dompet"],
		["枝", "えだ", "cabang"],
		["駅員", "えきいん", "Petugas Stasiun"],
		["この辺", "このへん", "Di sekitar sini"],
		["～辺", "～へん", "sebelah/sekitaran ~"],
		["このくらい", "このくらい", "Sebanyak ini"],
		["お先にどうぞ", "おさきにどうぞ", "Silahkan duluan"],
		["［ああ、］良かった", "［ああ、］よかった", "[ oh.. ] syukurlah"],
		["今の電車", "いまのでんしゃ", "Kereta sekarang"],
		["忘れ物", "わすれもの", "Barang tertinggal ( lupa )"],
		["～側", "～がわ", "Sisi ~"],
		["ポケット", "ポケット", "Kantong, saku"],
		["覚えていません", "おぼえていません", "Tidak ingat"],
		["網棚", "あみだな", "bagasi"],
		["確か", "たしか", "Semestinya, memang seperti demikian"],
		["地震", "じしん", "gempa bumi"],
		["壁", "かべ", "dinding"],
		["針", "はり", "jarum"],
		["指す", "さします", "Menunjuk"],
		["駅前", "えきまえ", "Depan Stasiun"],
		["西", "にし", "Barat"],
		["方", "ほう", "Cara"],
	],
	bab30: [
		["貼る", "はります", "Menempel"],
		["掛ける", "かけます", "Mengaitkan/menggantungkan"],
		["飾る", "かざります", "menghias"],
		["並べる", "ならべます", "Berbaris"],
		["植える", "うえる", "Menanam"],
		["戻す", "もどします", "mengembalikan"],
		["纏める", "まとめます", "Mengumpulkan"],
		["片付ける", "かたづけます", "Merapikan"],
		["仕舞う", "しまいます", "Menyimpan, merapikan"],
		["決める", "きめます", "Memutuskan"],
		["知らせる", "しらせます", "memberitahu, mengumumkan"],
		["相談する", "そうだんします", "Berkonsultasi"],
		["予習する", "よしゅうします", "untuk persiapan"],
		["復習する", "ふくしゅうします", "Ulasan, evaluasi"],
		["そのままにする", "そのままにする", "biarkan seperti itu"],
		["お子さん", "おこさん", "Anak ( orang lain )"],
		["授業", "じゅぎょう", "Pelajaran"],
		["講義", "こうぎ", "kuliah"],
		["ミーティング", "ミーティング", "pertemuan"],
		["予定", "よてい", "rencana"],
		["お知らせ", "おしらせ", "Mengumumkan"],
		["案内書", "あんないしょ", "Panduan, buku petunjuk"],
		["カレンダー", "カレンダー", "kalender"],
		["ポスター", "ポスター", "Poster"],
		["ゴミ箱", "ごみばこ", "Tempat sampah"],
		["人形", "にんぎょう", "boneka"],
		["花瓶", "かびん", "vas"],
		["鏡", "かがみ", "cermin"],
		["引き出し", "ひきだし", "laci"],
		["玄関", "げんかん", "Pintu gerbang"],
		["廊下", "ろうか", "Koridor"],
		["壁", "かべ", "dinding"],
		["池", "いけ", "kolam"],
		["交番", "こうばん", "Pos Polisi"],
		["元の所", "もとのところ", "Tempat asli"],
		["周り", "まわり", "lingkungan, sekitar"],
		["真ん中", "まんなか", "tengah"],
		["隅", "すみ", "sudut"],
		["まだ", "まだ", "belum"],
		["～程", "～ほど", "setara*"],
		["予定表", "よていひょう", "susunan acara"],
		["ご苦労さま", "ごくろうさま", "Terima kasih atas kerja kerasnya"],
		["希望", "きぼう", "harapan"],
		[
			"何かご希望がありますか",
			"なにかごきぼうがありますか",
			"apa yang anda harapkan/inginkan",
		],
		["ミューシカル", "ミューシカル", "Musikal"],
		["丸い", "まるい", "bulat"],
		["月", "つき", "Bulan"],
		["ある～", "ある～", "ada ~"],
		["地球", "ちきゅう", "Bumi"],
		["嬉しい", "うれしい", "senang"],
		["嫌［な］", "いや［な］", "tidak suka ( kirai na )"],
		["すると", "すると", "kemudian, dengan begitu"],
		["目が覚める", "めがさめます", "membuka mata"],
	],
	bab31: [
		["始まる", "はじまります［しきが～］", "dimulai ( upacara nya ~ )"],
		["続ける", "つづけます", "untuk melanjutkan"],
		["見つける", "みつけます", "menemukan"],
		["受ける", "うけます［しけんを～］", "Mendaftar ( ~ test )"],
		[
			"入学する",
			"にゅうがくします［だいがくに～］",
			"daftar/masuk sekolah ( ~ ke universitas )",
		],
		[
			"卒業する",
			"そつぎょうします［だいがくを～］",
			"lulus sekolah ( ~ universitas )",
		],
		["出席する", "しゅっせきします［かいぎに～］", "Hadir ( ~ rapat )"],
		["休憩する", "きゅうけいします", "Beristirahat"],
		["連休", "れんきゅう", "libur berturut-turut"],
		["作文", "さくぶん", "Cerita karangan"],
		["展覧会", "てんらんかい", "pameran"],
		["結婚式", "けっこんしき", "( Upacara ) Pernikahan"],
		["［お］葬式", "［お］そうしき", "Upacara pemakaman ( kremasi )"],
		["式", "しき", "Upacara"],
		["本社", "ほんしゃ", "kantor pusat"],
		["支店", "してん", "Kantor cabang"],
		["教会", "きょうかい", "Gereja"],
		["大学院", "だいがくいん", "Pasca Sarjana"],
		["動物園", "どうぶつえん", "Kebun binatang"],
		["温泉", "おんせん", "Air panas alami"],
		["お客［さん］", "おきゃく［さん］", "Tamu ( pelanggan )"],
		["誰か", "だれか", "Siapa, seseorang"],
		["～の方", "～のほう", "Yang ~"],
		["ずっと", "ずっと", "Jauh lebih"],
		["残る", "のこります", "Sisa, tinggal"],
		["月に", "つきに", "Sebulan"],
		["普通の", "ふつうの", "Biasa"],
		["インターネット", "インターネット", "Internet"],
		["村", "むら", "Desa"],
		["映画館", "えいがかん", "Bioskop"],
		["嫌［な］", "いや［な］", "Tidak suka ( kirai na )"],
		["空", "そら", "Langit"],
		["閉じる", "とじます", "Menutup"],
		["都会", "とかい", "Perkotaan"],
		["子どもたち", "こどもたち", "anak-anak"],
		["世界中", "せかいじゅう", "Di dalam dunia"],
		["自由に", "じゆうに", "bebas"],
		["集まる", "あつまります", "berkumpul"],
		["美しい", "うつくしい", "cantiknya"],
		["自然", "しぜん", "Alam"],
		["素晴らしさ", "すばらしさ", "Kemegahan"],
		["気がつく", "気がつきます", "Terbersit"],
	],
	bab32: [
		["運動する", "うんどうします", "Olahraga"],
		["成功する", "せいこうします", "keberhasilan"],
		["失敗する", "しっぱいします［しけんに～］", "Gagal ( ~ test )"],
		["合格する", "ごうかくします［しけんに～］", "Lulus ( ~ ujian )"],
		["戻る", "もどります", "Kembali"],
		["止む", "やみます［あめが～］", "Berhenti ( hujan nya ~ )"],
		["晴れる", "はれます", "Cerah"],
		["曇る", "くもります", "Berawan ( mendung)"],
		["吹く", "ふきます［かぜが～］", "Bertiup ( ~ angin )"],
		[
			"治る、直る",
			"なおります［びょうきが～］",
			"Menyembuhkan, kesembuhan ( ~ penyakit )",
		],
		["治る、直る", "なおります［こしょうが～］", "memperbaiki ( ~ kerusakan )"],
		["続く", "つづきます［ねつが～］", "(ber) kelanjutan ( panas nya ~ )"],
		["ひく", "ひきます［かぜを～］", "menarik, tarik ( masuk angin )"],
		["冷やす", "ひやします", "mendinginkan"],
		["心配［な］", "しんぱい［な］", "Khawatir [I]"],
		["十分［な］", "じゅうぶん［な］", "cukup]"],
		["おかしい", "おかしい", "Aneh"],
		["煩い", "うるさい", "berisik"],
		["火傷", "やけど", "Luka bakar"],
		["怪我", "けが", "Luka, cedera"],
		["咳", "せき", "batuk"],
		["インフルエンザ", "インフルエンザ", "influensa"],
		["空", "そら", "Langit"],
		["太陽", "たいよう", "Matahari"],
		["星", "ほし", "Bintang"],
		["月", "つき", "Bulan"],
		["風", "かぜ", "Angin"],
		["北", "きた", "Utara"],
		["南", "みなみ", "Selatan"],
		["西", "にし", "Barat"],
		["東", "ひがし", "timur"],
		["水道", "すいどう", "instalasi air ( PAM )"],
		["エンジン", "エンジン", "mesin"],
		["チーム", "チーム", "tim"],
		["今夜", "こんや", "malam ini"],
		["夕方", "ゆうがた", "Sore, petang"],
		["前", "まえ", "Sebelumnya"],
		["遅く", "おそく", "Terlambat, sudah larut"],
		["こんなに", "こんなに", "begitu"],
		["そんなに", "そんなに", "begitu"],
		["あんなに", "あんなに", "segitu"],
		["若しかしたら", "もしかしたら", "Jikalau, andai"],
		["それはいけません", "それはいけません", "Itu tidak bisa/boleh"],
		["オリンピック", "おりんぴっく", "Olimpiade"],
	],
	bab33: [
		["逃げる", "にげます", "melarikan diri"],
		["騒ぐ", "さわぎます", "Membuat kegaduhan"],
		["諦める", "あきらめます", "menyerah"],
		["投げる", "なげます", "melemparkan"],
		["守る", "まもります", "melindungi"],
		["上げる", "あげます", "meningkatkan"],
		["下げる", "さげます", "Menurunkan"],
		["伝える", "つたえます", "Menyampaikan, mengungkapkan"],
		[
			"注意する",
			"ちゅういします［くるまに～］",
			"Perhatikan, hati-hati ( ~ thd mobil )",
		],
		[
			"外す",
			"はずします［せきを～］",
			"*Lepas, keluar ( beranjak dari kursi )",
		],
		["だめ［な］", "だめ［な］", "Tidak baik/bagus"],
		["席", "せき", "Tempat Duduk"],
		["ファイト", "ファイト", "Pertarungan (fight )"],
		["マーク", "マーク", "Tanda ( mark )"],
		["ボール", "ボール", "bola"],
		["洗濯機", "せんたくき", "Mesin cuci"],
		["～機", "～き", "Mesin ~"],
		["規則", "きそく", "Aturan"],
		["使用禁止", "しようきんし", "Jangan gunakan"],
		["立入禁止", "たちいりきんし", "Dilarang masuk"],
		["入口", "いりぐち", "Pintu Masuk"],
		["出口", "でぐち", "Pintu Keluar"],
		["非常口", "ひじょうぐち", "pintu darurat"],
		["無料", "むりょう", "Gratis"],
		["本日休業", "ほんしつきゅうぎょう", "Libur ( hari ini )"],
		["営業中", "えいぎょうちゅう", "Buka (pelayanan)"],
		["使用中", "しようちゅう", "(sedang) Digunakan"],
		["～中", "～ちゅう", "Selang/selama ~"],
		["どういう", "どういう", "Jenis/macam/seperti apa"],
		["もう", "もう", "Sudah"],
		["あと～", "あと～", "setelah ~"],
		["駐車違反", "ちゅうしゃいはん", "Pelanggaran Parkir"],
		["そりゃあ", "そりゃあ", "jika begitu"],
		["～以内", "～いない", "dalam ~"],
		["警察", "けいさつ", "polisi"],
		["罰金", "ばっきん", "Denda"],
		["電報", "でんぽう", "Telegram"],
		["人々", "ひとびと", "orang-orang"],
		["急用", "きゅうよう", "Urusan Mendesak"],
		["打つ", "うちます［でんぽうを～］", "Mengetik ( ~ teleggram)"],
		["電報代", "でんぽうだい", "biaya telegram"],
		["出来るだけ", "できるだけ", "Sebisa mungkin"],
		["短く", "みじかく", "Pendek"],
		["また", "また", "lagi"],
		["例えば", "たとえば", "Sebagai contoh,"],
		["キトク", "キトク", "Minat, ketertarikan"],
		["重い病気", "おもいびょうき", "penyakit berat"],
		["明日", "あす", "besok"],
		["留守", "るす", "Jaga rumah"],
		["留守番", "るすばん", "Tugas jaga rumah"],
		["［お］祝い", "［お］いわい", "Ucapan selamat"],
		["亡くなる", "なくなる", "Mati"],
		["悲しみ", "かなしみ", "kesedihan"],
		["利用する", "りようします", "Gunakan untuk"],
	],
	bab34: [
		["磨く", "みがきます［はを］", "Menyikat ( ~ gigi )"],
		["組み立てる", "くみたてます", "Membangun, mendirikan, merangkai"],
		["折る", "おります", "Melipat"],
		[
			"気がつく",
			"きがつきます［わすれものに］",
			"Teringat ( ~ benda hilang/lupa )",
		],
		["付ける", "つけます［しょうゆを～］", "Menambahkan ( ~ kecap )"],
		["見つかる", "みつかります［かぎが～］", "Ditemukan [kunci ~]"],
		["する", "します［ネクタイを～］", "Mengenakan ( ~ dasi )"],
		["質問する", "しつもんします", "Bertanya"],
		["細い", "ほそい", "kurus, tipis"],
		["太い", "ふとい", "Gemuk, tebal"],
		["盆踊り", "ぼんおどり", "tari Bon Festival"],
		["スポーツクラブ", "スポーツクラブ", "Klub olahraga"],
		["家具", "かぐ", "mebel"],
		["キー", "キー", "Kunci"],
		["シートベルト", "シートベルト", "Sabuk pengaman"],
		["説明書", "せつめいしょ", "Buku Manual"],
		["図", "ず", "Gambar"],
		["線", "せん", "garis"],
		["矢印", "やじるし", "Tanda panah"],
		["黒", "くろ", "hitam"],
		["白", "しろ", "putih"],
		["赤", "あか", "Merah"],
		["青", "あお", "hijau"],
		["紺", "こん", "biru laut"],
		["黄色", "きいろ", "kuning"],
		["茶色", "ちゃいろ", "cokelat"],
		["醤油", "しょうゆ", "Kecap"],
		["ソース", "ソース", "Saus"],
		["～か～", "～か～", "~ Atau ~"],
		["昨夜", "ゆうべ", "Tadi malam"],
		["さっき", "さっき", "Baru saja"],
		["茶道", "さどう", "upacara minum teh"],
		["お茶をたてる", "おちゃをたてます", "Membuat teh"],
		["先に", "さきに", "Lebih dulu"],
		["載せる", "のせます", "Memuat, menaikan"],
		[
			"これでいいですか",
			"これでいいですか",
			"Bagaimana jika begini, Apakah ini OK?",
		],
		["苦い", "にがい", "Pahit"],
		[
			"親子どんぶり",
			"おやこどんぶり",
			"*Menu masakan Jepang. Sup ayam & telur diatas nasi",
		],
		["材料", "ざいりょう", "bahan"],
		["ー分", "ーぶん", "Satu bagian"],
		["鳥肉", "とりにく", "Daging ayam"],
		["ー個", "ーこ", "satu potong/ buah ( jumlah)"],
		["玉葱", "たまねぎ", "Bawang"],
		["４분의１", "４ぶんの１", "seper empat"],
		["調味料", "ちょうみりょう", "Penyedap rasa"],
		["鍋", "なべ", "Periuk"],
		["火", "ひ", "api"],
		["火にかける", "ひにかけます", "Menaruh di kompor"],
		["煮る", "にます", "Merebus"],
		["煮える", "にえます", "Matang (rebusan)"],
		["丼", "どんぶり", "semangkuk nasi"],
		["ーグラム", "ーグラム", "1 gram"],
	],
	bab35: [
		["咲く", "さきます［はなが～］", "Mekar, merekah ( bunga nya ~ )"],
		["変わる", "かわります［いろが～］", "Berubah ( ~ warna )"],
		["困る", "こまります", "Ke sulit an"],
		["付ける", "つけます［まるを～］", "Menambahkah ( ~ bulat )"],
		["拾う", "ひろいます", "Memungut"],
		[
			"かかる",
			"かかります［でんわが～］",
			"tersambung ( ~ telepon ) *telepon masuk",
		],
		["楽［な］", "らく［な］", "Mudah , menyenangkan"],
		["正しい", "ただしい", "benar"],
		["珍しい", "めずらしい", "langka"],
		["方", "かた", "Cara"],
		["向こう", "むこう", "Di sana"],
		["島", "しま", "pulau"],
		["村", "むら", "Desa"],
		["港", "みなと", "Pelabuhan"],
		["近所", "きんじょ", "Lingkungan sekitar ( tetangga )"],
		["屋上", "おくじょう", "Atap"],
		["海外", "かいがい", "luar negeri"],
		["山登り", "やまのぼり", "Mendaki gunung"],
		["ハイキング", "ハイキング", "Mendaki ( hiking )"],
		["機会", "きかい", "kesempatan"],
		["許可", "きょか", "Izin"],
		["丸", "まる", "Lingkaran"],
		["操作", "そうさ", "pengoperasian ( mesin )"],
		["方法", "ほうほう", "metode"],
		["設備", "せつび", "pemasangan, instalasi ( perlengkapan )"],
		["カーテン", "カーテン", "Tirai / gorden"],
		["紐", "ひも", "tali"],
		["蓋", "ふた", "tutup"],
		["葉", "は", "daun"],
		["曲", "きょく", "Lagu"],
		["楽しみ", "たのしみ", "Kesenangan"],
		["もっと", "もっと", "Lebih"],
		["初めに", "はじめに", "pertama"],
		[
			"これで終わります。",
			"これでおわります。",
			"dengan ini ( maka ) berakhir/selesai",
		],
		["それなら", "それなら", "jika demikian ( dalam hal itu )"],
		["夜行バス", "やこうバス", "Bis malam"],
		["旅行社", "りょこうしゃ", "Agen Travel/wisata"],
		["詳しい", "くわしい", "Detail / terperinci"],
		["スキー場", "スキーじょう", "Resor ski"],
		["朱", "しゅ", "Merah muda"],
		["交わる", "まじわります", "Memotong"],
		["諺", "ことわざ", "Peribahasa ( pepatah )"],
		["仲良くする", "なかよくします", "akrab"],
		["必要［な］", "ひつよう［な］", "Perlu"],
	],
	bab36: [
		["届く", "とどきます［にもつが～］", "tiba/sampai ( barangnya ~ )"],
		["出る", "でます［しあいに～］", "Tampil,bermain ( ~ di pertandingan )"],
		["打つ", "うちます［ワープロを～］", "Mengetik ( ~ Wapro )"],
		["貯金する", "ちょきんします", "Menabung"],
		["太る", "ふとります", "Menjadi gemuk"],
		["痩せる", "やせます", "menurunkan berat badan"],
		[
			"過ぎる",
			"すぎます［７じを～］",
			"Lebih , terlalu/melewati ( pukul 7 ~ )",
		],
		["慣れる", "なれます［しゅうかんに～］", "Terbiasa ( ~ kebiasaan )"],
		["硬い", "かたい", "Keras, kaku"],
		["軟らかい", "やわらかい", "Lembut, lembek"],
		["電子～", "でんし～", "(perangkat)~ elektrik"],
		["携帯～", "けいたい～", "ponsel ~"],
		["工場", "こうじょう", "pabrik"],
		["健康", "けんこう", "kesehatan"],
		["剣道", "けんどう", "Kendo ( seni pedang/beladiri )"],
		["毎週", "まいしゅう", "Setiap minggu"],
		["毎月", "まいつき", "bulanan"],
		["毎年", "まいとし（まいねん）", "Setiap tahun"],
		["やっと", "やっと", "*akhirnya (rampung)"],
		["可也", "かなり", "cukup,lumayan"],
		["必ず", "かならず", "kamu harus"],
		["絶対に", "ぜったいに", "pastinya"],
		["上手に", "じょうずに", "dengan lihainya"],
		["出来るだけ", "できるだけ", "Sebisa mungkin"],
		["この頃", "このごろ", "dewasa ini"],
		["～ずつ", "～ずつ", "~ demi ~"],
		["そのほうが～", "そのほうが～", "Lebih baik dari ~"],
		["ショパン", "ショパン", "Federick Chopin (komponis)"],
		["お客様", "おきゃくさま", "Pelanggan"],
		["特別[な]", "とくべつ[な]", "Spesial. khusus"],
		["していらっしゃいます", "していらっしゃる", "Sedang ~"],
		["水泳", "すいえい", "renang"],
		["～とか、～とか", "～とか、～とか", "seperti/semacam ~"],
		["タンゴ", "タンゴ", "Tango"],
		["チャレンジする", "チャレンジします", "Tantangan"],
		["気持ち", "きもち", "Perasaan"],
		["乗り物", "のりもの", "kendaraan"],
		["歴史", "れきし", "sejarah"],
		["ー世紀", "ーせいき", "satu abad"],
		["遠く", "とおく", "Jauh"],
		["汽車", "きしゃ", "Kereta api"],
		["汽船", "きせん", "Kapal uap/api"],
		["大勢の ～", "おおぜいの ～", "kerumunan ~"],
		["運ぶ", "はこびます", "Mengangkut"],
		["飛ぶ", "とびます", "melompat, terbang"],
		["安全[な]", "あんぜん[な]", "aman, nyaman"],
		["宇宙", "うちゅう", "ruang ngkasa"],
		["地球", "ちきゅう", "Bumi"],
		["ライト兄弟", "ライトきょうだい", "Wright Bersaudara"],
	],
	bab37: [
		["褒める", "ほめます", "memuji"],
		["叱る", "しかります", "Memarahi"],
		["誘う", "さそいます", "Undang"],
		["起こす", "おこします", "Membangunkan"],
		["招待する", "しょうたいします", "mengundang"],
		["頼む", "たのみます", "Meminta (pertolongan/bantuan)"],
		["注意する", "ちゅういします", "Memperhatikan"],
		["盗る", "とります", "Mencuri"],
		["踏む", "ふみます", "Menginjak"],
		["壊す", "こわします", "kerusakan"],
		["汚す", "よごします", "Menodai, mengotori"],
		["行なう", "おこないます", "Mengadakan"],
		["輸出する", "ゆしゅつします", "ekspor"],
		["輸入する", "ゆにゅうします", "untuk mengimpor"],
		["翻訳する", "ほんやくします", "menterjemahkan"],
		["発明する", "はつめいします", "Menciptakan, menemukan"],
		["発見する", "はっけんします", "Menemukan"],
		["設計する", "せっけいします", "rancangan"],
		["米", "こめ", "Beras"],
		["麦", "むぎ", "gandum"],
		["石油", "せきゆ", "Minyak (bumi)"],
		["原料", "げんりょう", "Bahan ( baku/mentah )"],
		["デート", "デート", "Wakuncar"],
		["泥棒", "どろぼう", "pencuri"],
		["警官", "けいかん", "Petugas kepolisian"],
		["建築家", "けんちくか", "arsitek"],
		["科学者", "かがくしゃ", "ilmuwan"],
		["漫画", "まんが", "Gambar kartun, komik"],
		["世界中", "せかいじゅう", "Seluruh dunia"],
		["～中", "～じゅう", "sedang berlangsung ~"],
		["～によって", "～によって", "berdasakan/menurut ~"],
		["よかったですね", "よかったですね", "Bagus ya.. ( Alhamdulillah"],
		["埋め立てる", "うめたてます", "Mengubur"],
		["技術", "ぎじゅつ", "Teknologi"],
		["土地", "とち", "tanah"],
		["騒音", "そうおん", "kebisingan"],
		["利用する", "りようします", "Menggunakan"],
		["アクセス", "アクセス", "mengakses"],
		["ー世紀", "ーせいき", "satu abad"],
		["豪華［な］", "ごうか［な］", "Mewah"],
		["彫刻", "ちょうこく", "Patung"],
		["眠る", "ねむります", "Mengantuk"],
		["彫る", "ほります", "mengukir"],
		["仲間", "なかま", "teman"],
		["そのあと", "そのあと", "setelah itu"],
		["一生懸命", "いっしょうけんめい", "Bersungguh sungguh"],
		["鼠", "ねずみ", "Tikus"],
		["一匹もいません", "いっぴきもいません", "Seekor pun tidak ada"],
	],
	bab38: [
		["育てる", "そだてます", "Mendidik"],
		["運ぶ", "はこびます", "Mengangkut"],
		["亡くなる", "なくなります", "Meninggal, mati"],
		["入院する", "にゅういんします", "dirawat di rumah sakit"],
		["退院する", "たいいんします", "Keluar Rumah Sakit"],
		["入れる", "いれます［でんげんを～］", "Memasukan ( ~ daya )"],
		["切れる", "きれます［でんげんを～］", "Mematikan ( ~ daya )"],
		["掛ける", "かけます［かぎを～］", "*Mengunci"],
		["気持ちがいい", "きもちがいい", "Merasa baik"],
		["気持ちが悪い", "きもちがわるい", "Perasaan buruk"],
		["大きな～", "おおきな～", "~ Besar (kata benda)"],
		["小さな～", "ちいさな～", "~ kecil (kata benda)"],
		["赤ちゃん", "あかちゃん", "Bayi"],
		["小学校", "しょうがっこう", "sekolah dasar"],
		["中学校", "ちゅうがっこう", "SMP"],
		["駅前", "えきまえ", "Depan Statsiun"],
		["海岸", "かいがん", "Pantai"],
		["嘘", "うそ", "Berbohong"],
		["書類", "しょるい", "Dokumen, berkas"],
		["電源", "でんげん", "Sumber Daya listrik"],
		["～製", "～せい", "dibuat -"],
		["［あ、］いけない", "［あ、］いけない", "[Oh,] tidak"],
		[
			"お先に［失礼します］",
			"おさきに［しつれいします］",
			"Permisi, saya duluan*",
		],
		["回覧", "かいらん", "Surat edaran"],
		["研究室", "けんきゅうしつ", "Laboratorium"],
		["きちんと", "きちんと", "Rapi, teliti"],
		["整理する", "せいりします", "merapikan"],
		["～という本", "～というほん", "Buku yang bernama/berjudul ~"],
		["ー冊", "ーさつ", "*satuan untuk buku"],
		["判子", "はんこ", "Stempel, *tanda tangan Jepang"],
		["押す", "おします［はんこを～］", "Tekan [segel Anda ~]"],
		["双子", "ふたご", "kembar"],
		["姉妹", "しまい", "saudari"],
		["５年生", "５ねんせい", "kelas 5"],
		["似ている", "にています", "mirip"],
		["性格", "せいかく", "Kepribadian"],
		["大人しい", "おとなしい", "Dewasa, tenang"],
		["世話をする", "せわをします", "Merepotkan"],
		["時間が経つ", "じかんがたちます", "memakan waktu"],
		["大好き［な］", "だいすき［な］", "kesukaan"],
		["ー点", "ーてん", "~ point"],
		["クラス", "クラス", "kelas"],
		["喧嘩する", "けんかします", "perkelahian, pertarungan"],
		["不思議［な］", "ふしぎ［な］", "misteri"],
	],
	bab39: [
		["答える", "こたえます［しつもんに～］", "Menjawab (~ pertanyaan)"],
		[
			"倒れる",
			"たおれます［ビルが～］",
			"Jatuh, tersungkur, pingsan ( Bill ~ )",
		],
		["焼ける", "やけます［うちが～］", "Terbakar ( bagian dalam ~ )"],
		["通る", "とおります［みちを～］", "Melalui [~ jalan]"],
		["死ぬ", "しにます", "mati"],
		["喫驚する", "びっくりします", "terkejut"],
		["がっかりする", "がっかりします", "kecewa"],
		["安心する", "あんしんします", "Aman, merasa tenang/lega"],
		["遅刻する", "ちこくします", "terlambat"],
		["早退する", "そうたいします", "Tinggalkan awal"],
		["喧嘩する", "けんかします", "Berkelahi"],
		["離婚する", "りこんします", "perceraian"],
		["複雑［な］", "ふくざつ［な］", "Rumit"],
		["邪魔［な］", "じゃま［な］", "mengganggu, risih"],
		["汚い", "きたない", "kotor"],
		["嬉しい", "うれしい", "senang"],
		["悲しい", "かなしい", "sedih"],
		["恥ずかしい", "はずかしい", "Malu"],
		["地震", "じしん", "gempa bumi"],
		["台風", "たいふう", "Topan, badai"],
		["火事", "かじ", "Kebakaran"],
		["事故", "じこ", "kecelakaan"],
		["［お］見合い", "［お］みあい", "Penjodohan"],
		["電話代", "でんわだい", "tagihan telepon"],
		["～代", "～だい", "~ Biaya"],
		["フロント", "フロント", "Depan ( front)"],
		["ー号室", "ーごうしつ", "Kamar/ruangan nomor 1"],
		["汗", "あせ", "Keringat"],
		["タオル", "タオル", "handuk"],
		["石鹸", "せっけん", "Sabun mandi"],
		["大勢", "おおぜい", "Banyak ( orang )"],
		[
			"お疲れ様でした",
			"おつかれさまでした",
			"Terima kasih atas kerja keras Anda",
		],
		["伺います", "うかがいます", "Menanyakan"],
		["途中で", "とちゅうで", "Di tengah-tengah"],
		["トラック", "トラック", "truk"],
		["ぶつかる", "ぶつかります", "Bertabrakan"],
		["並ぶ", "ならびます", "berbaris"],
		["大人", "おとな", "dewasa"],
		["洋服", "ようふく", "Pakaian ( eropa )"],
		["西洋化する", "せいようかします", "Gaya Barat"],
		["合う", "あいます", "Cocok"],
		["今では", "いまでは", "Sekarang"],
		["成人式", "せいじんしき", "Upacara orang dewasa"],
		[
			"焼ける",
			"やけます［パンが～］",
			"Membakar/ panggang ( ~ roti | rotinya matang )",
		],
		[
			"焼ける",
			"やけます［にくが～］",
			"Membakar/ panggang ( ~ daging | dagingnya matang )",
		],
	],
	bab40: [
		["数える", "かぞえます", "menghitung"],
		["測る、量る", "はかります", "Mengukur, menimbang"],
		["確かめる", "たしかめます", "Konfirmasi"],
		["合う", "あいます［サイズが～］", "Pas ( ukuran ~ )"],
		["出発する", "しゅっぱつします", "berangkat"],
		["到着する", "とうちゃくします", "Tiba, kedatangan"],
		["酔う", "よいます", "Mabuk"],
		["危険［な］", "きけん［な］", "berbahaya"],
		["必要［な］", "ひつよう［な］", "perlu"],
		["宇宙", "うちゅう", "Ruang angkasa"],
		["地球", "ちきゅう", "Bumi"],
		["忘年会", "ぼうねんかい", "pesta akhir tahun"],
		["新年会", "しんねんかい", "Pesta tahun Baru"],
		["二次会", "にじかい", "Pihak kedua"],
		["大会", "たいかい", "Turnamen"],
		["マラソン", "マラソン", "maraton"],
		["コンテスト", "コンテスト", "Kontes"],
		["表", "おもて", "Tampak/bagian depan"],
		["裏", "うら", "Tampak/bagian belakang"],
		["返事", "へんじ", "balasan"],
		["申し込み", "もうしこみ", "Daftar, registrasi"],
		["本当", "ほんとう", "Benar, sesungguhnya"],
		["間違い", "まちがい", "kesalahan"],
		["傷", "きず", "luka"],
		["ズボン", "ズボン", "celana"],
		["長さ", "ながさ", "panjangnya"],
		["重さ", "おもさ", "bobot"],
		["高さ", "たかさ", "tinggi"],
		["大きさ", "おおきさ", "Besaran"],
		["［ー］便", "［ー］びん", "Penerbangan ( ~ pertama/satu )"],
		["ー号", "ーごう", "nomor ( ~ satu )"],
		["ー個", "ーこ", "buah/pcs ( satu ~ )"],
		["ー本", "ーほん（ーぽん、ーぼん）", "Batang ( satu ~ )"],
		["ー杯", "ーはい（ーぱい、ーばい）", "Gelas ( satu ~ )"],
		["ーキロ", "ーキロ", "kilogram ( satu ~ )"],
		["ーグラム", "ーグラム", "Gram ( satu ~ )"],
		["ーセンチ", "ーセンチ", "Sentimeter ( satu ~ )"],
		["ーミリ", "ーミリ", "Milimeter ( satu ~)"],
		["～以上", "～いじょう", "Lebih dari ( lebih dari ~ )"],
		["～以下", "～いか", "Kurang dari ( kurang dari ~ )"],
		["さあ", "さあ", "OK, kita mulai"],
		["雪祭り", "ゆきまつり", "Festival salju"],
		["どうでしょうか", "どうでしょうか", "Bagaimana tentang itu"],
		["クラス", "クラス", "kelas"],
		["テスト", "テスト", "uji"],
		["成績", "せいせき", "Kelas/ tingkatan"],
		["ところで", "ところで", "ngomong-ngomong"],
		["いらっしゃる", "いらっしゃいます", "Datang"],
		["様子", "ようす", "Penampilan"],
		["事件", "じけん", "Kejadian"],
		["オートバイ", "オートバイ", "sepeda motor"],
		["爆弾", "ばくだん", "bom"],
		["積む", "つみます", "Tumpukan"],
		["運転手", "うんてんしゅ", "sopir"],
		["離れた", "はなれた", "Berjauhan, berpisah"],
		["が", "が", "Tapi"],
		["急に", "きゅうに", "Tiba - tiba, mendadak"],
		["動かす", "うごかします", "Menggerakan"],
		["一生懸命", "いっしょうけんめい", "Bersungguh sunggguh"],
		["犯人", "はんにん", "Tersangka"],
		["手に入れる", "てにいれます", "untuk memperoleh"],
		["今でも", "いまでも", "Sekarang pun"],
		["噂する", "うわさします", "Kabar gosip"],
	],
	bab41: [
		["頂く", "いただきます", "menerima"],
		["下さる", "くださります", "Memberikan"],
		["やる", "やります", "melakukan"],
		["呼ぶ", "よびます", "Memanggil"],
		["取り替える", "とりかえます", "Mengganti, menukar"],
		["親切にする", "しんせつにします", "bersikap ramah"],
		["可愛い", "かわいい", "imut, lucu"],
		["お祝い", "おいわい", "perayaan"],
		["お年玉", "おとしだま", "Lotre, undian"],
		["［お］見舞い", "［お］みまい", "Layatan, menjenguk"],
		["興味", "きょうみ", "tertarik"],
		["情報", "じょうほう", "informasi"],
		["文法", "ぶんぽう", "tatabahasa"],
		["発音", "はつおん", "pengucapan"],
		["猿", "さる", "monyet"],
		["餌", "えさ", "Makanan hewan"],
		["玩具", "おもちゃ", "mainan"],
		["絵本", "えほん", "Buku bergambar"],
		["絵葉書", "えはがき", "Kartu Pos Bergambar"],
		["ドライバー", "ドライバー", "Obeng (driver)"],
		["ハンカチ", "ハンカチ", "saputangan"],
		["靴下", "くつした", "kaus kaki"],
		["手袋", "てぶくろ", "sarung tangan"],
		["指輪", "ゆびわ", "cincin"],
		["バッグ", "バッグ", "tas"],
		["祖父", "そふ", "kakek"],
		["祖母", "そぼ", "nenek"],
		["孫", "まご", "Cucu"],
		["おじ", "おじ", "paman"],
		["おじさん", "おじさん", "Paman atau Pak"],
		["おば", "おば", "Bibi"],
		["おばさん", "おばさん", "Bibi"],
		["一昨年", "おととし", "Dua tahun yang lalu"],
		["はあ", "はあ", "Ohh.."],
		["申し訳ありません", "もうしわけありません", "Maaf*"],
		["預る", "あずかります", "Menitipkan"],
		["先日", "せんじつ", "Hari sebelumnya *kemarin"],
		["助かる", "たすかります", "terbantu, tertolong"],
		["昔話", "むかしばなし", "Dongeng, cerita lama"],
		["ある～", "ある～", "ada ~"],
		["男", "おとこ", "Lelaki"],
		["子どもたち", "こどもたち", "anak-anak"],
		["苛める", "いじめます", "mengganggu, membulli"],
		["亀", "かめ", "penyu"],
		["助ける", "たすけます", "Menolong, membantu"],
		["［お］城", "［お］しろ", "Kastil"],
		["お姫様", "おひめさま", "putri"],
		["楽しく", "たのしく", "Senang"],
		["暮らす", "くらします", "kehidupan"],
		["陸", "りく", "daratan"],
		["すると", "すると", "dengan demikian"],
		["煙", "けむり", "asap"],
		["真っ白［な］", "まっしろ［な］", "putih"],
		["中身", "なかみ", "Isi, dalaman"],
	],
	bab42: [
		["包む", "つつみます", "Membungkus"],
		["沸かす", "わかします", "mendidih"],
		["混ぜる", "まぜます", "Mencampur"],
		["計算する", "けいさんします", "menghitung"],
		["厚い", "あつい", "tebal"],
		["薄い", "うすい", "tipis"],
		["弁護士", "べんごし", "pengacara"],
		["音楽家", "おんがくか", "Musisi"],
		["子どもたち", "こどもたち", "anak-anak"],
		["二人", "ふたり", "Dua orang"],
		["教育", "きょういく", "pendidikan"],
		["歴史", "れきし", "sejarah"],
		["文化", "ぶんか", "budaya"],
		["社会", "しゃかい", "Masyarakat, sosial"],
		["法律", "ほうりつ", "hukum"],
		["戦争", "せんそう", "Peperangan"],
		["平和", "へいわ", "perdamaian"],
		["目的", "もくてき", "Tujuan"],
		["安全", "あんぜん", "keamanan"],
		["論文", "ろんぶん", "Disertasi"],
		["関係", "かんけい", "Hubungan"],
		["ミキサー", "ミキサー", "Pengaduk ( mixer )"],
		["薬缶", "やかん", "ketel"],
		["栓抜き", "せんぬき", "pembuka botol"],
		["缶切り", "かんきり", "pembuka kaleng"],
		["風呂敷", "ふろしき", "Kain pembungkus ( pakaian )"],
		["缶詰", "かんづめ", "Makanan kaleng"],
		["算盤", "そろばん", "Sempoa, dekak dekak"],
		["体温計", "たいおんけい", "Termometer"],
		["材料", "ざいりょう", "bahan"],
		["石", "いし", "batu"],
		["ピラミッド", "ピラミッド", "piramida"],
		["データ", "データ", "data"],
		["ファイル", "ファイル", "File"],
		["ある～", "ある～", "ada ~"],
		["一生懸命", "いっしょうけんめい", "Bersungguh sungguh"],
		["なぜ", "なぜ", "Mengapa"],
		["国連", "こくれん", "Persatuan negara-negara"],
		["ローン", "ローン", "Pinjaman (loan)"],
		["セット", "セット", "set"],
		["あと", "あと", "juga, lalu, kemudian"],
		["カップラーメン", "カップラーメン", "Mie instan Cup"],
		["インスタントラーメン", "インスタントラーメン", "Mie instan"],
		["鍋", "なべ", "Periuk"],
		["丼", "どんぶり", "semangkuk nasi"],
		["食品", "しょくひん", "Bahan makanan"],
		["調査", "ちょうさ", "Riset"],
		["カップ", "カップ", "cangkir"],
		["また", "また", "Lagi"],
		["～の代わりに", "～のかわりに", "sebagai pengganti~"],
		["どこででも", "どこででも", "di manapun"],
		["今では", "いまでは", "(adapun) sekarang"],
	],
	bab43: [
		[
			"増える",
			"ふえます［ゆしゅつが～］",
			"Meningkat, bertambah ( ekspor nya ~ )",
		],
		["減る", "へります［ゆしゅつが～］", "Berkurang, menurun ( ekspor nya ~ )"],
		["上がる", "あがります［ねだんが～］", "Naik [harga yang ~]"],
		["下がる", "さがります［ねだんが～］", "Turun ( ~ harga )"],
		["切れる", "きれます［ひもが～］", "Putus ( ~ talinya )"],
		["取れる", "とれます［ボタンが～］", "Lepas ( ~ kancing )"],
		["落ちる", "おちます［にもつが～］", "Terjatuh ( ~ barang )"],
		["なくなる", "なくなります［ガソリンが～］", "Habis ( ~ bensin )"],
		["丈夫［な］", "じょうぶ［な］", "Kuat, kokoh"],
		["変［な］", "へん［な］", "Aneh"],
		["幸せ［な］", "しわせ［な］", "Bahagia"],
		["うまい", "うまい", "Enak, lihai"],
		["まずい", "まずい", "Tak enak"],
		["つまらない", "つまらない", "Membosankan"],
		["ガソリン", "ガソリン", "bensin"],
		["火", "ひ", "api"],
		["暖房", "だんぼう", "Penghangat"],
		["冷房", "れいぼう", "Pendingin"],
		["センス", "センス", "merasakan"],
		["今にも", "いまにも", "sekarang juga, segera"],
		["わあ", "わあ", "Wow"],
		["会員", "かいいん", "Anggota"],
		["適当［な］", "てきとう［な］", '"Sesuai kondisi" spontan, senyamanya'],
		["年齢", "ねんれい", "usia"],
		["収入", "しゅうにゅう", "pendapatan"],
		["ぴったり", "ぴったり", "Cocok, pas"],
		["その上", "そのうえ", "Bahkan"],
		["と言う", "といいます", "Berkata ~"],
		["薔薇", "ばら", "Mawar"],
		["ドライブ", "ドライブ", "Mengemudi, mendorong (drive)"],
	],
	bab44: [
		["泣く", "なきます", "menangis"],
		["笑う", "わらいます", "tertawa"],
		["乾く", "かわきます", "Mengeringkan"],
		["濡れる", "ぬれます", "Menjadi basah"],
		["滑べる", "すべります", "Tergelincir"],
		["起きる", "おきます［じこが～］", "Terjadi [kecelakaan ~]"],
		["調節する", "ちょうせつします", "Menyetel, menyesuaikan"],
		["安全［な］", "あんぜん［な］", "Aman"],
		["丁寧［な］", "ていねい［な］", "Sopan"],
		["細かい", "こまかい", "Terperinci"],
		["濃い", "こい", "Tebal"],
		["薄い", "うすい", "tipis"],
		["空気", "くうき", "udara"],
		["涙", "なみだ", "Air mata"],
		["和食", "わしょく", "Makanan Jepang"],
		["洋食", "ようしょく", "Makanan Barat ( Eropa )"],
		["おかず", "おかず", "Makanan pendamping"],
		["量", "りょう", "jumlah"],
		["ー倍", "ーばい", "Satu kali (lipat)"],
		["半分", "はんぶん", "Setengah"],
		["シングル", "シングル", "tunggal"],
		["ツイン", "ツイン", "kembar"],
		["たんす", "たんす", "Lemari"],
		["洗濯物", "せんたくもの", "Cucian"],
		["理由", "りゆう", "Alasan"],
		["どうなさいますか", "どうなさいますか", "Bagaimana, ada apa, kenapa?"],
		["カット", "カット", "Memotong ( cut )"],
		["シャンプー", "シャンプー", "sampo"],
		[
			"どういうふうになさいますか",
			"どういうふうになさいますか",
			"Akan menjadi seperti apa/bagaimana?",
		],
		["ショート", "ショート", "pendek"],
		[
			"～みたいにしてくだい",
			"～みたいにしてください",
			"Tolong lakukan seperti ~",
		],
		[
			"これでよろしいでしょうか",
			"これでよろしいでしょうか",
			"Apakah benar (dengan) seperti ini?",
		],
		[
			"［どうも］お疲れさまでした",
			"［どうも］おつかれさまでした",
			"(terima kasih) atas kerjasamanya",
		],
		["嫌がる", "いやがります", "Enggan"],
		["また", "また", "Juga, lagi"],
		["順序", "じゅんじょ", "Prosedur, tata tertib"],
		["表現", "ひょうげん", "Ekspresi"],
		["例えば", "たとえば", "Sebagai contoh,"],
		["別れる", "わかれます", "Berpisah"],
		["これら", "これら", "Ini (jamak)"],
		["縁起が悪い", "えんぎがわるい", "Kurang beruntung, nasib buruk"],
	],
	bab45: [
		["謝る", "あやまります", "minta maaf"],
		["あう", "あいます［じこに～］", "Bertemu ( ~ kecelakaan )"],
		["信じる", "しんじます", "percaya"],
		["用意する", "よういします", "mempersiapkan"],
		["キャンセルする", "キャンセルします", "Membatalkan"],
		["旨く行く", "うまくいきます", "berjalan lancar"],
		["保証書", "ほしょうしょ", "Jaminan"],
		["領収書", "りょうしゅうしょ", "resi"],
		["贈物", "おくりもの", "Hadiah, barang kiriman"],
		["間違い電話", "まちがいでんわ", "Panggilan salah sambung"],
		["キャンプ", "キャンプ", "kamp"],
		["係", "かかり", "Keterikatan"],
		["中止", "ちゅうし", "Penghentian"],
		["点", "てん", "Point"],
		["レバー", "レバー", "tuas"],
		["［ー円］札", "［ーえん］さつ", "Pecahan/lembaran ( ~ 1 yen)"],
		["ちゃんと", "ちゃんと", "Dengan baik/benar, tepat"],
		["急に", "きゅうに", "mendadak"],
		["楽しみにしている", "たのしみにしています", "Aku tak sabar untuk"],
		["以上です", "いじょうです", "Sekian (itu saja)"],
		["係員", "かかりいん", "petugas"],
		["コース", "コース", "Rute"],
		["スタート", "スタート", "Start"],
		["ー位", "ーい", "Peringkat pertama, ke-1"],
		["優勝する", "ゆうしょうします", "kemenangan"],
		["悩み", "なやみ", "Kegelisahan"],
		["目覚まし［時計］", "めざまし［とけい］", "jam alarm"],
		["眠る", "ねむります", "ngantuk (tidur)"],
		["目が覚める", "めがさめます", "Membuka mata (bangun tidur)"],
		["大学生", "だいがくせい", "mahasiswa"],
		["回答", "かいとう", "jawaban"],
		["鳴る", "なります", "(burung) berkicau"],
		["セットする", "セットします", "Disetting, disiapkan, disetel"],
		["其れでも", "それでも", "Walaupun demikian"],
	],
	bab46: [
		["焼く", "やきます", "Bakar/panggang"],
		["渡す", "わたします", "menyerahkan"],
		["帰って来る", "かえってきます", "Kembali pulang"],
		["出る", "でます［バスが～］", "Keluar, beroperasi (Bisnya ~ )"],
		["留守", "るす", "Keluar rurmah"],
		["宅配便", "たくはいびん", "Jasa ekspedisi barang"],
		["原因", "げんいん", "Sebab"],
		["注射", "ちゅうしゃ", "injeksi"],
		["食欲", "しょくよく", "nafsu makan"],
		["パンフレット", "パンフレット", "Pamflet"],
		["ステレオ", "ステレオ", "stereo"],
		["此方", "こちら", "sini"],
		["～の所", "～のところ", "Tempat ~"],
		["丁度", "ちょうど", "Tepat, persis, pas"],
		["たった今", "たったいま", "baru saja"],
		[
			"今いいでしょうか",
			"いまいいでしょうか",
			"Apakah boleh/berkenan jika sekarang (ada waktu?)",
		],
		["ガスサービスデンター", "ガスサービスセンター", "Gas Service Center"],
		["ガスレンジ", "ガスレンジ", "Kompor Gas"],
		["具合", "ぐあい", "Kondisi"],
		["どちら様でしょうか", "どちらさまでしょうか", "Maaf, ini siapa"],
		["向かう", "むかいます", "OTW"],
		["お待たせしました", "おまたせしました", "Maaf saya membuat Anda menunggu"],
		["知識", "ちしき", "pengetahuan"],
		["宝庫", "ほうこ", "Harta"],
		[
			"手に入る",
			"てにはいります［じょうほうが～］",
			"Mendapatkan (~informasi)",
		],
		["システム", "システム", "sistem"],
		["例えば", "たとえば", "Sebagai contoh,"],
		["キーワード", "キーワード", "kata kunci"],
		["一部分", "いちぶぶん", "Satu bagian"],
		["入力する", "にゅうりょくします", "memasukkan"],
		["秒", "びょう", "detik"],
		["出る", "でます［ほんが～］", "Terbit/rilis ( bukunya ~ )"],
	],
	bab47: [
		["集まる", "あつまります［ひとが～］", "Berkumpul [ orang ~ ]"],
		["別れる", "わかれます［ひとが～］", "Menyebar [ Orang ~ ]"],
		["長生きする", "ながいきします", "Panjang umur"],
		[
			"する",
			"します［おと／こえが～］［あじが～］［においが～］",
			"Tercium (aroma, bau), terdengar (suara)",
		],
		["指す", "さします［かさを～］", "Menyerahkan, memberikan [ ~ payung ]"],
		["ひどい", "ひどい", "Mengerikan"],
		["怖い", "こわい", "takut"],
		["天気予報", "てんきよほう", "Prakiraan Cuaca"],
		["発表", "はっぴょう", "Pengumuman"],
		["実験", "じっけん", "Percobaan"],
		["人口", "じんこう", "populasi"],
		["匂い", "におい", "bau"],
		["科学", "かがく", "Ilmu pengetahuan, sains"],
		["医学", "いがく", "Kedokteran"],
		["文学", "ぶんがく", "literatur"],
		["パトカー", "パトカー", "Mobil patroli"],
		["救急車", "きゅうきゅうしゃ", "ambulans"],
		["賛成", "さんせい", "Setuju"],
		["反対", "はんたい", "Berlawanan"],
		["男性", "だんせい", "pria"],
		["女性", "じょせい", "Wanita"],
		["どうも", "どうも", "Terima kasih"],
		["～によると", "～によると", "Menurut ~"],
		["恋人", "こいびと", "Kekasih"],
		["婚約する", "こんやくします", "Pertunangan"],
		["相手", "あいて", "Lawan"],
		["知り合う", "しりあいます", "Berkenalan"],
		["平均寿命", "へいきんじゅみょう", "Usia rata rata"],
		["比べる", "くらべます［だんせいと～］", "Dibandingkan [~ laki-laki]"],
		["博士", "はかせ", "Profesor"],
		["脳", "のう", "otak"],
		["ホルモン", "ホルモン", "hormon"],
		["化粧品", "けしょうひん", "Kosmetik"],
		["調べ", "しらべ", "diperiksa"],
		["化粧", "けしょう", "dandan"],
	],
	bab48: [
		["降ろす、下ろす", "おろします", "Menurunkan"],
		["届ける", "とどけます", "Mengirimkan, menyampaikan"],
		["世話をする", "せわをします", "Merepotkan"],
		["嫌［な］", "いや［な］", "Menyebalkan"],
		["厳しい", "きびしい", "Ketat"],
		["塾", "じゅく", "Kursus"],
		["スケジュール", "スケジュール", "Susunan acara"],
		["生徒", "せいと", "siswa"],
		["者", "もの", "Orang"],
		["入管", "にゅうかん", "Imigrasi"],
		["再入国ビザ", "さいにゅうこくビザ", "Re-entry visa"],
		["自由に", "じゆうに", "bebas"],
		["～間", "～かん", "selama ~"],
		["いいことですね", "いいことですね", "Ini adalah hal yang baik"],
		["お忙しいですか", "おいそがしいですか", "Apakah sedang sibuk?"],
		["久しぶり", "ひさしぶり", "lama tidak bertemu"],
		["営業", "えいぎょう", "Penjualan"],
		["それまでに", "それまでに", "sampai saat itu"],
		["構いません", "かまいません", "tidak apa-apa"],
		["楽しむ", "たのしみます", "Selamat bersenang-senang"],
		["元々", "もともと", "Asal mula"],
		["ー世紀", "ーせいき", "satu abad"],
		["代わりをする", "かわりをします", "Nambah"],
		["スピード", "スピード", "kecepatan"],
		["競走する", "きょうそうします", "Lomba"],
		["サーカス", "サーカス", "Sirkus"],
		["芸", "げい", "Trik"],
		["美しい", "うつくしい", "Cantik ( wajah )"],
		["姿", "すがた", "Penampilan"],
		["心", "こころ", "jantung"],
		["捉える", "とらえます", "Menangkap"],
		["～によって", "～によって", "Menurut, berdasarkan ~"],
	],
	bab49: [
		[
			"勤める",
			"つとめます［かいしゃに～］",
			"Mengabdi (bekerja) [ ~ di perusahaan ]",
		],
		["休む", "やすみます", "beristirahat"],
		[
			"掛ける",
			"かけます［いすに～］",
			"Menempelkan, menggantungkan [ ~ dikursi ]",
		],
		["過ごす", "すごします", "menghabiskan"],
		["寄る", "よります［ぎんこうに～］", "Mampir [~ ke bank]"],
		["いらっしゃる", "いらっしゃいます", "Datang"],
		["召し上がる", "めしあがります", "Makan"],
		["おっしゃる", "おっしゃります", "mengatakan"],
		["為さる", "なさいます", "melakukan"],
		["ご覧に なる", "ごらんに なります", "Melihat"],
		["ご存じです", "ごぞんじです", "Mengetahui"],
		["あいさつ", "あいさつ", "Salam pembuka"],
		["灰皿", "はいざら", "asbak"],
		["旅館", "りょかん", "penginapan"],
		["会場", "かいじょう", "Tempat bertemu"],
		["バス停", "バスてい", "pemberhentian bus"],
		["貿易", "ぼうえき", "Perdagangan luar negeri"],
		["～様", "～さま", "Tuan, Nyonya ~"],
		["帰りに", "かえりに", "Dalam perjalanan pulang"],
		["たまに", "たまに", "Terkadang"],
		["ちっとも", "ちっとも", "Tidak semuanya"],
		["遠慮なく", "えんりょなく", "Terima, tidak meolak"],
		["ー年ー組", "ーねん ーくみ", "Selama tahun selama perakitan"],
		["では", "では", "Baiklah, jika demikian"],
		["出す", "だします［ねつを～］", "mengeluarkan, meredakan [ ~ demam ]"],
		["よろしく お伝え ください", "よろしく おつたえ ください", "Titip salam"],
		["失礼いたします", "しつれいいたします", "permisi"],
		["講師", "こうし", "Dosen"],
		["多くの～", "おおくの～", "Banyak ~"],
		["作品", "さくひん", "Karya"],
		["授賞する", "じゅしょうします", "Menghadiahkan"],
		["世界的に", "せかいてきに", "Secara dunia"],
		["作家", "さっか", "Penulis"],
		["～でいらっしゃる", "～でいらっしゃいます", "Datang ~"],
		["長男", "ちょうなん", "putra sulung"],
		["障害", "しょうがい", "Kendala, gangguan *disabilitas"],
		["お持ちです", "おもちです", "Memiliki"],
		["作曲", "さっきょく", "Komposer"],
		["活動", "かつどう", "Aktivitas"],
		["それでは", "それでは", "Jika demikian"],
		["東京大学", "とうきょうだいがく", "The University of Tokyo"],
	],
	bab50: [
		["参る", "まいります", "Datang, pergi *sopan"],
		["居る", "おります", "Ada ( manusia & binatang )"],
		["頂く", "いただきます", "menerima"],
		["申す", "もうします", "Ucap, kata *sopan"],
		["致す", "いたします", "bentuk sopan dari します"],
		["拝見する", "はいけんします", "Melihat, inspeksi *sopan"],
		["存じる", "ぞんじます", "Mengtahui *sopan"],
		["伺う", "うかがいます", "Mendengar, bertanya * sopan"],
		["お目にかかる", "おめにかかります", "Bertemu *sopan"],
		["ご座る", "ございます", "ada *bentuk sopan dari あります"],
		["～でご座います", "～でございます", "Bentuk sopan dari です"],
		["私", "わたくし", "saya"],
		["ガイド", "ガイド", "panduan"],
		["お宅", "おたく", "Kediaman"],
		["郊外", "こうがい", "Pinggiran kota"],
		["アルバム", "アルバム", "album"],
		["再来週", "さらいしゅう", "2 minggu yang akan datang"],
		["再来月", "さらいげつ", "2 bulan yang akan datang"],
		["再来年", "さらいねん", "2 tahun yang akan datang"],
		["半年", "はんとし", "Setengah tahun"],
		["最初に", "さいしょに", "Pertama tama"],
		["最後に", "さいごに", "Pada akhirnya"],
		["ただ今", "ただいま", "Baru saja *saya pulang"],
		["江戸東京博物館", "えどとうきょうはくぶつかん", "Edo-Tokyo Museum ※"],
		["緊張する", "けんちょうします", "gugup"],
		["放送する", "ほうそうします", "Siaran (acara tv)"],
		["撮る", "とります［ビデオに～］", "Ambil [~ dalam video]"],
		["賞金", "しょうきん", "Hadiah"],
		["自然", "しぜん", "Alam"],
		["きりん", "きりん", "Kirin"],
		["象", "ぞう", "gajah"],
		["頃", "ころ", "Waktu"],
		["叶う", "かないます［ゆめが～］", "Terkabul ( mimpi yang ~ )"],
		[
			"一言宜しいでしょうか",
			"ひとことよろしいでしょうか",
			"sepatah kata, kesan pesan ( apakah berkenan untuk mengucapkan ~ )",
		],
		["協力する", "きょうりょくします", "bekerja sama"],
		["心から", "こころから", "Dari hati, sungguh sungguh"],
		["感謝する", "かんしゃします", "Terima kasih *sopan"],
		["［お］礼", "［お］れい", "(ucapan) penghormatan"],
		["拝啓", "はいけい", '"dengan hormat", "Yth" ( dalam surat )'],
		["美しい", "うつくしい", "cantiknya"],
		[
			"お元気でいらっしゃいますか",
			"おげんきでいらっしゃいますか",
			"Apa kabar * sopan dr おげんきですか。",
		],
		["迷惑をかける", "めいわくをかけます", "Merepotkan"],
		["生かす", "いかします", "Memelihara"],
		["［お］城", "［お］しろ", "Kastil"],
		["敬具", "けいぐ", "Salam Hormat"],
	],
};
